### ISSUE TITLE
Can't build samples

### ISSUE THREAD

**Issue by ziem** [sockeqwe/mosby#10]
Today I cloned your repo and now I'm trying to run samples. I don't know why, but gradle can't build them. I'm receiving following errors:

e.g. **sample** project
> /mosby/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/MvpActivity.java
> Error:(20, 32) error: cannot find symbol class MosbyActivity
> Error:(29, 67) error: cannot find symbol class MosbyActivity
> /mosby/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/layout/MvpFrameLayout.java
> Error:(7, 19) error: package butterknife does not exist
> /mosby/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/layout/MvpLinearLayout.java
> Error:(7, 19) error: package butterknife does not exist
> /mosby/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/layout/MvpRelativeLayout.java
> Error:(7, 19) error: package butterknife does not exist
> /mosby/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/lce/LceAnimator.java
> ...

I'm using Android Studio 1.2 Build 3. Why can't I build them? Can you help me?

**Comment by sockeqwe** [comment]
Im facing the same problem with Android Studio 1.2 
It seems that there are some internal issues with Annotation Processing.

However, this error only occurs on first app start or if you clean / rebuild your project. If you simply press the green Play button to compile and run the sample it should work without any compilation errors.

Let me know if that works on your machine as well.

**Comment by ziem** [comment]
Thanks. I tried cleaning, rebuilding, syncing gradle and running project in random order but unfortunately it's still not working.

Do you have any other ideas?

**Comment by TechFreak** [comment]
Yep, I'm having the same issue

**Comment by sockeqwe** [comment]
but pressing the "Green Play Button" works, doesn't it?

**Comment by sockeqwe** [comment]
I installed Android Studio 1.1.0, but still get the same error. I don't know exactly what the problem is (I guess something with annotation processing) but simply pressing the "Play button" to compile and run works fine for me.

Ensure that you have pulled the latest version:

Could you try to compile it from command line:
```groovy
./gradlew assemble --stacktrace
```

If you just want to have a look at the sample apps live on your android phone you can download the `apk` sample files from here:
https://db.tt/ycrCwt1L
https://db.tt/3fVqVdAz
https://db.tt/z85y4fSY

**Comment by TechFreak** [comment]
here is a gist of the gradle stacktrace: https://gist.github.com/62ff4714235bdd7aaced.git

It seems to be complaining about the support library but I do have version 22.0.0 installed on my system. In fact I'm using the exact same version on other projects.

My suspicion is that the variables declared on the rootProject with the versions of each library are not being processed correctly by gradle. I'm gonna do some testing and report back my results. BTW I'm using windows @ziem are you also using windows?

**Comment by sockeqwe** [comment]
Strange. maybe with an clean:
```groovy
./gradlew clean assemble --stacktrace
```

Btw. I'm working on mac osx.

**Comment by ziem** [comment]
I'm using OS X (Mavericks). Pressing green play button doesn't work. I also tried both commands - the same errors occurred.
Thanks for apks ;).

**Comment by IgorGanapolsky** [comment]
I am getting similar issues.  Gradle build spits out the following errors:
>Error:(19, 10) error: package rx does not exist
Error:(20, 29) error: package rx.android.schedulers does not exist
Error:(21, 21) error: package rx.schedulers does not exist
Error:(32, 39) error: cannot find symbol class Observable
where T is a type-variable:
T extends Object declared in class AndroidSchedulerTransformer
Error:(32, 20) error: cannot find symbol class Observable
where T is a type-variable:
T extends Object declared in class AndroidSchedulerTransformer

I am on Android Studio 1.2 Beta 3.  What is going on??

**Comment by sockeqwe** [comment]
I will strip out the samples of the library project. There seems to be a problem with annotation processing in multiple modules (the sample modules uses annotation porcessing). However, just pressing the "green play button" (and ignoring any previous error messages from console) works just fine on my mac book with android studio 1.2 Beta 3.

**Comment by ziem** [comment]
@sockeqwe that's strange. I'm also using Mac OS X and pressing green button does nothing. Maybe Android Studio cached something from your previous builds?

**Comment by sockeqwe** [comment]
@ziem Really strange! I already checked that, but it still works after doing a clean.
Even from commandline with
`./gradlew clean assemble --stacktrace` it compiles without any problems.

**Comment by ziem** [comment]
I used other computer (OS: Mavericks, AS: 1.2 Beta) to run mosby. I cloned repo then I opened project using "Open existing Android Studio project" and chose root build.gradle. After syncing/building I pressed play and I got errors similar to @TechFreak stacktrace then I pressed play button again, now I got errors with MosbyActivity. Pressed few times more - the same result. I also tried `./gradlew clean assemble --stacktrace` - still the same.

**Comment by TechFreak** [comment]
Tried removing the definition of versions for each libraries from the root gradle file, and using the exact values on each project, but it still doesn't work.

I tried checking out latest updates from a Linux pc, and got a different error: https://gist.github.com/dee73a2513a1f7e53617

It seems to be complaining in the :core-dagger1:androidJavadocs task. Is there a way to skip javadocs generation?

**Comment by TechFreak** [comment]
Ok, I think I've found the issue and a possible workaround. Using my linux pc I switched from Java 8 to Java 7, I got a lot of warnings about javadocs but the samples built just fine.

This (http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html) seems to be the issue, apparently Java 8 is more strict about javadocs than java7, and that's what we are seeing here. I'll try to check back on my windows pc to see if switching to java 7 solves the issue there as well.

I see 2 solutions to make this work on Java 8, first is to fix all of the javadoc warnings (there are a lot) or second is to disable javadoc lint from the gradle scripts. @sockeqwe not sure which one would you prefer? but I can help you either way.

If anyone else can canfirm if switching to java 7 solves their issues it would be great!

**Comment by sockeqwe** [comment]
OMG! It's true! Javadoc is the problem!
In Java 7 javadoc errors result in warnings. Java8 is more strict and will abort compiling.

@TechFreak  Thank you very much!
I removed javadoc generation temporarly. Could you please pull the master branch and check if that works on your machine?

I tried to disable java doc lint by using 
```groovy
task androidJavadocs(type: Javadoc) {
    failOnError false
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
  }
```

but it doesn't work right now.

However, I will try to find a solution for them (fixing the javadoc line errors is also an option )

What command did you run to get the javadoc lint errors?

**Comment by IgorGanapolsky** [comment]
@sockeqwe Thanks for the suggestion to `failonError false`.  That did the trick for me.  Such a convoluted problem with a such a simple fix!  I can continue to use Java8 now.  Have some bitcoin $1 on me @changetip.

**Comment by changetip** [comment]
Hi @sockeqwe, @IgorGanapolsky sent you a Bitcoin tip worth 4,474 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/721509)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by ziem** [comment]
@sockeqwe Thanks - last commit solves problem :+1: .

**Comment by TechFreak** [comment]
@sockeqwe Thanks! that fixed it, I can build perfectly from my windows box using java 8 and the latest version from master. BTW the mail example is awesome!

**Comment by sockeqwe** [comment]
@TechFreak @ziem @IgorGanapolsky I apologize for the inconvenience!
@IgorGanapolsky Thanks for the bitcoin :+1:  but I prefer a real beer whenever we will meet us :)

Btw. The mail example is a work in progress and not finisehed yet. I publish a blog post about the mail app example with some tips of how to use mosby in a real world app.

**Comment by IgorGanapolsky** [comment]
It would be awesome if you could augment the mail sample with scrolling tabs.  That would pretty much complete the gamut of Material Design + MVP pattern + dependency injection + RXJava.

**Comment by sockeqwe** [comment]
if I find time I will add "profiles" for mail senders, but I'm not sure what the tabs should contain ^^

or 

are you asking me about how to implement an activity with tabs in mvp, i.e. the number of tabs and type of fragment the tabs will display are loaded dynamically i.e. from a server?

**Comment by IgorGanapolsky** [comment]
I am interested in implementing tabs with Toolbar in MVP.  Your second
point...

**Comment by sockeqwe** [comment]
I cant promise to implement, but I try to find time.

Actually, with mosby it's just an MvpLceActivity, where the "Content" is a `LinearLayout` containing  `Tabbar` and `ViewPager`. The "data" is a list of "tabs" like 

```java
class TabsData {
     String name;  // The name displayed in the tabbar
     String fragmentType;  // some kind of mapping from "foo" to "FooFragment"
}
```

Each Fragment in the ViewPager has it's own MVP thing ... So Activity uses MVP to control the `Tabbar` `PagerAdapter` and `ViewPager`  and each "tab" is a Fragment having it's own MVP thing ...

Hope that helps

**Comment by IgorGanapolsky** [comment]
It's a start :)  I'm trying to keep it from getting complicated.  Google's
iosched source code implements tabs in a very convoluted way.  So I was
wondering if MVP would simplify this process...

Thanks,
Igor
