### ISSUE TITLE
Why does MvpBasePresenter uses WeakReference

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#102]
originally asked by @Tiny-Times as a comment on another (not related) issue, hence I have moved his question to this new created issue:

> i want to know why there is a need to use weak references.
>
> public abstract class MvpBasePresenter implements MvpPresenter {
> private WeakReference viewRef;
> @Override
> public void attachView(V view) { }
> protected V getView() { }
> protected boolean isViewAttached() { }
> @Override
> public void detachView(boolean retainInstance) { }
> }

> forexample activity：When the back, “ondestory” is sure to be executed, so the “detachView” will be  executed.

**Comment by sockeqwe** [comment]
@Tiny-Times It is just an implementation detail that should prevent memory leaks in case someone overrides mosby's default behaviour (or delegate) and forget to call `detachView()`.

So as you already have said correctly, if you use `MvpBasePresenter` with other Mosby default components than `detachView()` and `attachView()` should be called correctly and there would be no need to use a `WeakReference`. I only use `WeakReference` to prevent memory leaks on customization / misusing Mosby.

As already said, it's just an implementation detail of `MvpBasePresenter`. Feel free to write your own `BasePresenter` class without `WeakReference`.

**Comment by Tiny-Times** [comment]
Thank you. I've got it.
