### ISSUE TITLE
Are there problems with FragmentStatePagerAdapter?

### ISSUE THREAD

**Issue by T0bbes** [sockeqwe/mosby#103]
Hi,

regarding the question on [Stackoverflow](http://stackoverflow.com/questions/34437121/mosby-mvp-fragmentstatepageradapter-npe).
Are there any problems with 'FragmentStatePagerAdapter'? 
The `createPresenter` method is never called. If i replace the `MvpFragment` with the "normal" Fragment my app is working

**Comment by sockeqwe** [comment]
Hm, 
not tested yet with `FragmentStatePagerAdapter` but it should work.
Do you have a project here on github so that I don't have to write a demo to debug from scratch?

**Comment by sockeqwe** [comment]
Hi again, I have added another example for ViewPager (in [sample](https://github.com/sockeqwe/mosby/tree/master/sample)) with and without `FragmentStatePagerAdapter` ():

Everything works as expected ... 

https://github.com/sockeqwe/mosby/blob/master/sample/src/main/java/com/hannesdorfmann/mosby/sample/mvp/lce/viewpager/ViewPagerActivity.java

So I'm closing this issue... I will try to help you on stackoverflow ...
