### ISSUE TITLE
Presenter not created if Fragment has no UI

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#104]
Add a  check to determine if `Fragment.onViewCreated()` has been called. This is requires as internally this method will create the presenter. If the fragment has no UI (`Fragment.onCreateView()` not implemented). However, `onDestroyView()` will be called, which tries to detach the view from non existing presenter.

Adding a runtime check for that should be easy. #103

**Comment by InTwoMinds** [comment]
Dirty workaround if anyone stumbles here:

```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    super.onCreateView(inflater, container, savedInstanceState);
    onViewCreated(null, savedInstanceState);
    return null;
}
```

**Comment by sockeqwe** [comment]
A Runtime exception will be thrown in next Version 2.0.1 (commimg very
soon) tellimg you that Mosby doesn't support UI less fragments...

InTwoMinds <notifications@github.com> schrieb am Sa., 20. Feb. 2016, 02:45:
