### ISSUE TITLE
Allow non textview errorview in LceAnimator.showErrorView

### ISSUE THREAD

**Issue by legarspol** [sockeqwe/mosby#107]
Hi !
It might be useful to make `LceAnimator.showErrorView(View, View, TextView)` become `LceAnimator.showErrorView(View, View, View)`

**Comment by sockeqwe** [comment]
Agree

legarspol <notifications@github.com> schrieb am Di., 12. Jan. 2016, 17:32:

**Comment by antslava** [comment]
+1

**Comment by sockeqwe** [comment]
Done, will be released in February
