### ISSUE TITLE
How to use the MvpLceRxPresenter with 4 Horizontal RecyclerViews in the same screen.

### ISSUE THREAD

**Issue by jjvargas** [sockeqwe/mosby#108]
I have used MvpLceRxPresenter  when I have 1 RecyclerView in the screen but how to use it if I have 4 different RecyclerViews

**Comment by sockeqwe** [comment]
That's a very vague question. That depends on your use and how you load data ...
EITHER 
you see each RecyclerView as its own independent MvpView  (use LCEView only if all three states (showLoading(), showError(), showContent() are reachable and in each independent MvpView on screen) with its own MvpPresenter that loads items to display just for this single RecyclerView

OR

Use one single View for the whole screen that loads the data for all 4 RecyclerViews and gives the result back to the View in a optimized PresentationModel (generated by the Presenter) like this:
```java
interface MyView extends MvpLceView<MyPresentationModel> 
```
```java
class MyPresentationModel {
   List<Item> row1; // displayed afterwards by first RecyclerView
   List<Item> row2 // displayed by second RecyclcerView
   List<Item> row3 // displayed by third RecyclcerView
   List<Item> row4 // displayed by fourth RecyclcerView
}
```
```java
class MyPresenter extends MvpLcePresenter<MyView> {

    public void loadData(boolean pullToRefresh) {
        retrofit.loadSomething() // RxJava observable
           .map( singleData) -> transformToPresentationModel(singleData) )
           .subscribe (  ... ); // showLoading() , showError(), showContent()
    }

    private MyPresentationModel transformToPresentationModel(List<Item> singleData){
         MypPresentationModel presentationModel = new MyPresentationModel();
         for (Item i : singleData){
             // fill presentationModel
         }
         return presentationModel;
    }
} 
```

**Comment by sockeqwe** [comment]
btw @jjvargas  I would appreciate if you would ask those kind of questions on stackoverflow, because it's not Mosby related, it's more general MVP question. I also have an eye on questions tagged with [mosby](http://stackoverflow.com/questions/tagged/mosby). Furthermore, stackoverflow is well indexed by google, so it's easier for others to find your question / answer on stackoverflow and you might also get  better answers and other suggestions / opinions ... Thanks
