### ISSUE TITLE
id's configureable - What about getters for views and bundle keys 

### ISSUE THREAD

**Issue by legarspol** [sockeqwe/mosby#109]
Hi !

Here we are with a fragment with two nested fragment.
The 3 fragments are all using the mvp and also the viewstate stytem.

If we use Lce we first meet the problem that there is several contentView errorView and loadingView in the same Android view.
We can then stop using Lce classes, copy past the lce logic code just to change the view ids binded.

But we then have the problem with Viewstate which use the same key:
public static final String KEY_BUNDLE_VIEW_STATE =
      "com.hannesdorfmann.mosby.mvp.viewstate.ViewState.bundlekey";

Well then you can override `public void saveInstanceState(Bundle out);` and `public AbsParcelableLceViewState<D, V> restoreInstanceState(Bundle in)` from `RestorableViewState` but since you don't want to call super you have to pray for not having some generalization inbetween of that interface you wanted to use.

What about using getter and setter for next version ?

```
public @ResId int getContentViewId() {
return R.id.contentView;
}
```

and 

```
string getViewstateBundleKey();
```

**Comment by sockeqwe** [comment]
Hm, does that problem really happen in a real life app (I havent tested it yet)? I don't have tested yet, but `findViewById()` will always been called on the relative "root" layout.

If you have a structure like this:
- MvpLceViewStateActivity (then it uses activity root layout and will find activity R.id.contentView )  
   - MvpLceViewStateFragment (then it uses fragment root layout and fill find fragments R.id.contentView
         - MvpLceViewStateFragment (then it uses fragment root layout and fill find fragments child R.id.contenView)

And the same should be true for the ViewState that is bundled into the Bundle. But every Fragment and Activity has it's own bundle, so there should be no conflict ...

I already have used `MvpLceViewStateActivity`  containing a `MvpLceViewStateFragment` without any conflicts.

So are you really facing a conflict in there?

**Comment by legarspol** [comment]
I can confirm one thing:
FragmentA not retaining has a fragment xml node instancing fragmentB not retaining.
If both fragment have loadingView etc... defined it does clash.

Couldn't reproduce the viewstate clash.

**Comment by sockeqwe** [comment]
I will investigate on that in detail and come back to you (by the end of this week).

**Comment by sockeqwe** [comment]
Hi,  sorry for the late response.

I have implemented a little example that shows that nested LCE views are not causing conflicts
https://github.com/sockeqwe/NestedLceViews

Basically I have the following hierarchy
 - MvpLceViewStateActivity with LinearLayout as contentView
   - MvpLceViewStateFragment with ViewPager as contentView
      - MvpLceViewStateActivity (fragment in ViewPager) with ListView as contentView

All of them have loadingView, errorView and contentView (the same ids).

Can you explain how you are getting a conflict?

**Comment by sockeqwe** [comment]
@legarspol Can this issue be closed?

**Comment by legarspol** [comment]
Hi, I'll not be available to send you a sample project until I think 2
weeks.

**Comment by sockeqwe** [comment]
Great, thanks! I will leave this issue open until then

**Comment by legarspol** [comment]
Hi !
Sorry for the delay.
Here is the problem I ran into:
https://github.com/legarspol/NestedFragment

Basically id clashes if the son appear too soon in the view.
You can look at the two branches in the repo. It happens either by including the fragment from xml or programmatically.

Switching the position of the fragment or fragment holder with the textview should make the project compile.

**Comment by sockeqwe** [comment]
Hi, thanks for the sample project.
Unfortunately, I'm busy this week. I will have a look at your sample project at weekend.

At first glance without having dove deep into your code) it seems that the problem is not "mosby" related, but you are trying grab View's from Fragments from your Activity, don't you? And then you will do that by root `activities.findViewById()` which obviously would always return the first element with the given id.

**Comment by legarspol** [comment]
Hi,
It's not what i'm trying to do. It was sadly happen.
We are talking about the fact that by not letting the dev define it's own contentView, loadingView and errorView ids we run into clashs.
As fragments and host activity both use the same R.id.contentView some configuration break the app as the host lce get sub fragments ids instead of the activities ones.

**Comment by sockeqwe** [comment]
Hi,
as already said, I haven't looked yet deep into your sample (once again, thanks for that).

**I am willing to allow people to bring their own id's in** as starting in Mosby 3.0 .

However, I do have to verify that there are no clashes at all which I will do this on the upcoming weekend (otherwise giving other id's is just a workaround for a much bigger problem).

**Comment by sockeqwe** [comment]
View id's are configureable in upcoming  `3.0`
