### ISSUE TITLE
Sample Mail App crashes

### ISSUE THREAD

**Issue by kokaz** [sockeqwe/mosby#11]
Hi,

The sample app crashed when the developer option "Don't keep activities" is on.
I don't have time to investigate on it so I notify you :)

PS: However the sample app is really nice!

**Comment by sockeqwe** [comment]
Jep, it's a work in progress and not finished yet (I had to merge everything on master branch because of another problem #10)
However, thanks for reporting!

Btw. In case you are interested in the mail sample, I will publish soon a blog post about it with some tips of how to use mosby in a real app

**Comment by javajack** [comment]
Yeah. The blih post is something which me and many other must be looking forward to.

Some points to cover.
How to interact between mosby activity and normal activity.

Does rxjava makes sense to be used all the time ?

What should be the database storage mechanism ?

Answers to all such questions from your perspective , your best practice :)
