### ISSUE TITLE
cannot resolve symbol AppCompatActivity

### ISSUE THREAD

**Issue by hram** [sockeqwe/mosby#112]
In com.hannesdorfmann.mosby.mvp.MvpActivity class I have error "cannot resolve symbol AppCompatActivity"

If I create new project in AS with AppCompatActivity this project works well.

How can I fix this?

**Comment by sockeqwe** [comment]
How does your `build.gradle` looks like?

**Comment by hram** [comment]
This happend jast after git clone without any modificatios.

**Comment by sockeqwe** [comment]
Which example are you trying to start?
So when you do a gradle sync (or just press the green play button to launch the app) you will see an error log in android studio. Can you please post the full log / stacktrace here

**Comment by hram** [comment]
I do not start any example. Jast open project in AS and if I onen MvpActivity class AppCompatActivity displayed red collor and import android.support.v7.app.AppCompatActivity is also red

**Comment by sockeqwe** [comment]
Try `Build --> Clean Project`

**Comment by hram** [comment]
I dont now why but broject builbs and "Sample" app runs withour any error (
Excuse my for troubling. I dont now why AS behaves like that

**Comment by sockeqwe** [comment]
I have no clue :smile: 
Glad that it works
