### ISSUE TITLE
Can i set the emptyView?

### ISSUE THREAD

**Issue by leesunghyun** [sockeqwe/mosby#113]
If the data of the response in the development of MvpLceActivity does not exist, I think that want to display the emptyView on the screen.
In mosby support it?
For example getView().showEmpty() no plans to add a method?

**Comment by sockeqwe** [comment]
Maybe, although I think this is to use case specific. LCE is not only used with RecyclerView / ListView where such "empty view" makes sense. 

I have to think about it ... It would be nice to hear other users opinion about this.

**Comment by sockeqwe** [comment]
What I really dislike is to have a feature like this build in which cause other users to add code / or views in xml to work properly but its not used by the majority. So I would say that it is something that should be implemented by each user as needed.

**Comment by leesunghyun** [comment]
The kind of View might be different In the screen that use the LCE,
Because I think that data is always exist.
I think is that emptyView is necessary.
If there is no data In the screen that use the LCE.
Do you think that there is not common that you set a emptyView ?

**Comment by sockeqwe** [comment]
for instance I do have a LCE where a ViewPager is the `contentView` and I load "tabs" from backend. If there is a empty list of tabs I would forward this to errorView.

**Comment by sockeqwe** [comment]
Is too use case specific, therefore will close this for now ...

**Comment by SuperThomasLab** [comment]
@sockeqwe Is there a possibility that you could reopen this issue? I really need an emptyView as I want to show a different view for 'no items' and 'error'. If there are no items, it does NOT mean it is an error.

**Comment by sockeqwe** [comment]
no ... This is super easy to implement by your own.
Just add an additional `emptyView` in your LCE xml layout.

The override `showContent()` of your LCE Activity / Fragment like this:

```java
MyLceActivity extends MvpLceActivity {

   View emptyView;
   MyAdapter adapter; // RecyclerViewAdapter   

   @Override
    public void showContent(){
       super.showContent();
       if (adapter.getItemCount() == 0){
           emptyView.setVisibility(View.VISIBLE);
       } else {
           emptyView.setVisibility(View.GONE); 
       }
    }

   @Override
   public void showError(){
      super.showError(); 
      emptyView.setVisibility(View.GONE);
   }

  @Override 
   public void showLoading(boolean pullToRefresh){
       super.showLoading(pullToRefresh);
       emptyView.setVisibility(View.GONE);
   }
}
```
