### ISSUE TITLE
Cannot have one Fragment two more Presenter?

### ISSUE THREAD

**Issue by leesunghyun** [sockeqwe/mosby#116]
![](http://hannesdorfmann.com/mosby/images/mvp-gmail-candidates.png "image")

This picture is four of the fragment exists in one of the activities?
If i want to reuse business logic(presenter) i should create new fragment?
For example, i need in a fragment two more business logic(presenter).

**Comment by sockeqwe** [comment]
Presenter is not business logic, presenter is just the connection between business logic (the blue boxes) and the view. Presenter just tells the View what to display, so Presenter kind of coordinates the view. 

For example, `MailProvider` (Business logic) is used by `InboxPresenter` and `MailPresenter` to either display a list of mails (InboxView) or to display a single Mail (MailView). 

So creating entirely new Presenters is cheap. If you want to reuse a Presenter you can do that too. Presenter programms against a View Interface. So if you want a new View (i.e. Fragment) that displays the same data just in another way simply implement the View interface on your new Fragment and reuse the same presenter.

**Comment by leesunghyun** [comment]
Thanks for answers!
