### ISSUE TITLE
Wrong image for Australia in sample-flow

### ISSUE THREAD

**Issue by hzsweers** [sockeqwe/mosby#119]
![flow-mainactivity-03012016170121](https://cloud.githubusercontent.com/assets/1361086/13447291/3d85df6c-dfcf-11e5-9e94-9df5fd22c87b.png)

Top right image is not in Australia, rather it's the town of Willemstad.

Source: I'm from Willemstad, and can confirm I'm not Australian ;)

**Comment by hzsweers** [comment]
Oh wait I see they all just use the same images. 🎶 ignore meeeee 🎶

**Comment by sockeqwe** [comment]
haha :+1: 

Yes, all the images are just hardcoded (except the flag).
I haven't time to search for images for each country or for an image service without an api key so I simply hardcoded them (if you know such a service I would be more than happy to use that one instead).

Btw: Willemstad seems to be a pretty nice city! I think I have to stop by there next time I'm in this area.
