### ISSUE TITLE
Problem adding mosby as a dependency in android library module

### ISSUE THREAD

**Issue by fmnstr** [sockeqwe/mosby#121]
Hello, I will start by saying that I am a fan of your work. I really like your approach in architecting Android apps.

I face the following issue trying to add mosby library in a new project. I am adding mosby as a dependency in android library module to provide base classes for my app module.
`    compile 'com.hannesdorfmann.mosby:mvp:2.0.1'
    compile 'com.hannesdorfmann.mosby:viewstate:2.0.1' `
The only part from mvp that is being added is mvp-common-2.0.1 resulting in errors compiling missing MvpFragment.

I use A.Studio 2.0 Beta 6, Gradle plugin 2.0, Build tools version 23.0.2.
I tried both A.Studio stable version 1.5.1, Gradle plugin 1.5 , mvp library v.2.0.0

When I added the library as a dependency in the app module everything was fine and all needed dependencies resolved just fine.

**Comment by sockeqwe** [comment]
Do you mean a java library project or android library project?

**Comment by fmnstr** [comment]
Android library project `apply plugin: 'com.android.library'`

**Comment by sockeqwe** [comment]
that is strange, I use it a lot in library modules and never had an issue and I can't see how Mosby should be causing a problem in library modules only ...

Have you tried clean your project? Maybe there are some other dependencies or annotation processors that may cause an issue?

**Comment by fmnstr** [comment]
Yes, that is strange. I have used it a while back on version 1 on another project with no issues. There are other dependencies on annotation processors.
The bizarre thing that urged me to open the issue was that I created a new project with empty activity. new library module and I just added the mvp dependencies. No code nothing, just default stuff from the a.studio wizards. Then I saw in external libraries that only mvp-common got resolved. When I moved it in app's module all resolved fine.

I have done a lot of clean, rebuild, invalidate caches for 2 days now but I 'll look some more.

**Comment by fmnstr** [comment]
Ok.. The test project managed to import MvpFragment from mvp even if it only shows mvp-common in external libraries. I'll dig around adding-removing libraries with annotation processors to see what might be the problem in my main project.

**Comment by sockeqwe** [comment]
Hm, I had similar issues with other libraries where some classes couldn't have been  found in Android Studio. In my case an Annotation Processor has caused this issue. 
If you do `Build -> Rebuild Project` I got some errors mainly saying me that the classes could not have been found. But somewhere in between all those errors there was a little error message produced by an annotation processor. After having fixed that all the other "classes" has been found and the project compiled successfully.

Maybe you are facing the same / similar issue?

**Comment by fmnstr** [comment]
Ok strange things happen. I had moved my base classes to app module along with mosby dependencies to continue my work. I just moved them back to the library module along with the dependencies to test any annotation processor issues. Everything resolved and the app run with no issues.. 
I'll consider this closed and thank you for your time trying to help me.

**Comment by sockeqwe** [comment]
\_(ツ)_/¯
