### ISSUE TITLE
Android support annotations for java modules

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#127]
`mvp-common` module contains base classes / interfaces like  `MvpView`, `MvpPresenter`, `MvpBasePresenter` is distributed as simple jar and not an android library. 
The intention was to be able to use plain old java modules for presentation layers downwards that don't have dependencies to android sdk to achieve faster build times and reusable modules that could been shared with other java applications (for example desktop applications).

The problem with shipping `mvp-common` as jar is that containing classes like `MvpView` and `MvpPresenter` are annotated with annotations from  `android.support.annotation` like `@NonNull`, `@UIThread` etc. but  `android.support.annotation` is not available from a public repo. The whole android toolchain assumes that those kind of libraries are in a special local "android maven repository" on the developers machine.

So if you want to use `mvp-common` as depenedency in a java module / project (not android project) you have to ensure that `android.support.annotation` is in your build path, otherwise you can't compile.

The are two solutions to fix this problem:
 - add a the url to your local "android maven repository" manually (see [here](https://github.com/sockeqwe/mosby/blob/master/mvp-common/build.gradle#L8) how to do it in gradle without hardcoding paths)
 - we could add "stubs" in Mosby for those annotations used in `mvp-common`

Since nobody has complained about this issue yet, we assume that there are not much people building java modules (not android) with Mosby dependency. Hence, for now we are doing nothing :smile: to address this issue.

If you face this issue and the suggested solution (url to your local "android maven repository") doesn't work for you, leave a comment here on this issue and we will see what we can do to address this issue in Mosby.

**Comment by sockeqwe** [comment]
not worth the effort ...

**Comment by wildsmith** [comment]
I just want to say thank you for this post. I came across this issue in one of my projects and tried so much before leveraging the first option you had listed in your post. Thanks again.

**Comment by SuperThomasLab** [comment]
Hello @sockeqwe,
I'm using Mosby in a Java module and used your workaround above. It works and am able to compile the project. However, I would like to be able to put the Views and Presenters in the Java module. Isn't it better to move `MvpBasePresenter` to the `mvp-common` module? How should I be able to use `MvpBasePresenter`?
Thanks, Thomas

**Comment by sockeqwe** [comment]
Once it is in mvp-common it is also available for other modules like MVI if
I remember correctly. Not sure what the best solution would be here. I
personally think that you should copy and paste it in your own project as I
would not really like to introduce modules if there is not a high demand
for it (you are the first person Im aware.of using Mosby for java
applications as well).

SuperThomasLab <notifications@github.com> schrieb am Fr., 16. Juni 2017,
20:57:

**Comment by SuperThomasLab** [comment]
Thanks for your quick reply. I'll just copy the class into my project as
you suggested.

Btw: I'm using Mosby for an Android app and not (yet) a Java app. The
reason why I am compiling in a Java module is so I have the flexibility to
reuse the code for another platform/app based on Java. Maybe someday in the
future I want to port my app to another platform, and this way I only need
to do program the UI stuff, as the main app logic is programmed in pure
Java.

Intel developed some software called Multi-OS Engine. It allows you to
program Android and iOS apps in pure Java. (All within Android Studio!) I
have no idea how stable their software is but it looks really promising. If
you want to check it out, here's a link: https://multi-os-engine.org/

Regards,
Thomas
