### ISSUE TITLE
CursorLoader and MVP

### ISSUE THREAD

**Issue by mradzinski** [sockeqwe/mosby#133]
Hi, CursorLoader requires of a Context, and from an MVP perspective this Loader should be inside the presenter, however, passing a Context to the presenter is a really bad idea since it should not know about the Activity itself but treat it as a view, plus having a Context there can lead to memory leaks.

How would you handle the situation were you need to use a CursorLoader to load data? Where would you implement it?

Cheers!

**Comment by lenguyenthanh** [comment]
I don't think Loader should be inside the presenter. Presenter on MVP should handle presenter logic only, not other logics like loading data from network or local. 

Btw, if you want, you can use Application Context, or you can inject Context to use it on Presenter(which is a bad practice, I don't suggest to use this).

**Comment by mradzinski** [comment]
So, assuming that the presenter should not be in charge of loading data then obviously the model is the best choice to implement the loader, right? So my question prevails. The CursorLoader class requires a Context to be passed in its constructor, and neither a Model or a Presenter should hold any instances of a Context, specially the Model since it should not have any knowledge of any other layer than the Presenter...

**Comment by lenguyenthanh** [comment]
You definitely can use `Context` in your model (your business logic), and you should use Dependency Injection to inject `Context` to your model. There are many job cannot be done without `Context` so it's okay to use `Context` on another layer then View layer.
