### ISSUE TITLE
Does mosby handle situation when View is de-attached on screen rotation?

### ISSUE THREAD

**Issue by Try4W** [sockeqwe/mosby#134]
What if some async work in `Presenter` will be finished in the moment when View is de-attached?

For example:
1. User click 'do work' button
2. `Presenter` does request to server(and doesn't stop work in de-attach method)
3. Screen rotation in progress and `View` de-attached
4. `Presenter` receives response from the server and wants to notify `View` about it. But there is no attached `View`.
5. `View` is attached(in another orientation) and restore itself from `ViewState`. Response is executed, but View is not changed.

Is it real situation? Or `de-attaching` and `attaching` `View ` is happening in one moment?

There is my solutaion:

```
public abstract class BaseMvpPresenter<V extends MvpView> extends MvpBasePresenter<V> {

    private Queue<Runnable> executeOnAttachQueue = new LinkedList<>();

    public void executeOnAttachView(Runnable runnable) {
        executeOnAttachQueue.add(runnable);
    }

    public void executeGranted(Runnable runnable) {
        if(isViewAttached()) {
            runnable.run();
        } else {
            executeOnAttachView(runnable);
        }
    }

    @Override
    public void attachView(V view) {
        super.attachView(view);
        while (!executeOnAttachQueue.isEmpty()) {
            Runnable nextElement = executeOnAttachQueue.remove();
            nextElement.run();
        }
    }
}
```

But do I really need it?

**Comment by sockeqwe** [comment]
See github pages FAQ:
http://hannesdorfmann.com/mosby/summary/


> Can the Presenter and its view be out of sync during a screen orientation change?
>
> Excellent question. Mosby assumes that all interaction from Presenter with the View happens on android’s main UI thread. Hence the answer is no that cannot happen since screen orientation changes are executed on the main UI thread as well. So either is a screen orientation executed completely (view reattached) or the presenter invokes the views method after view is reattached since both run on main UI thread or the presenter invokes the views methods before starting screen orientation change.

So as long as your Presenter invokes View methods on main UI thread your solution is not needed.

**Comment by Try4W** [comment]
I got it. If I use Retrofit&RxJava, then I don't need things like `isViewAttached()` or my solution.
```
        api.getProjects(accountManager.getUserId())
                .subscribeOn(ioScheduler)
                .observeOn(AndroidSchedulers.mainThread())
```
As my code always will run on Android UI Thread. But, your [example](https://github.com/sockeqwe/mosby/blob/master/sample-mail/src/main/java/com/hannesdorfmann/mosby/sample/mail/login/LoginPresenter.java) calls `isViewAttached()` method anyway. Is it mistake or there is any reason for it?

I read below:

> Why do I need isViewAttached() check in MvpBasePresenter
> 
> In a perfect world you wouldn’t need this check. As already said, in Mosby all interaction from Presenter to View happens on android’s main UI thread. Since screen orientation changes are also executed on the main UI thread it is not possible to run into the scenario where view is detached while presenter still wants to update the UI, right? However, we are not living in a perfect world. Let’s say you use an AsyncTask to make an http request and the Presenter gets the result back and updates the View. If you forget to cancel this AsyncTask after the View has been destroyed (i.e. your apps user press the back button, presenter.detachView(false) will be called) then you can run into the scenario that the View is detached from Presenter and then the Presenter gets the result back from AsyncTask and wants to update the View which is null (because detached). So the isViewAttached() check is basically some kind of safety net. In a perfect implementation you wouldn’t need it (presenter - view interaction on main thread, cancel all async background task when view gets destroyed etc.), but in general I would say it wouldn’t hurt to drive with a safety net.

But still don't get it.

Is there any forum about Mosby to discuss questions like this?

**Comment by sockeqwe** [comment]
If you are sure that you are unsubscribing your RxJava subscription properly in `presenter.detachView(false)` then you shouldn't need `isViewAttached()`

I did so in the examples (and also in my production code) because
> but in general I would say it wouldn’t hurt to drive with a safety net.

There is no Mosby forum. I would like to see those kind of question asked on Stackoverflow because it is better searchable through google so it is easier to discover those question and answers for others.

I have seen (right now) that you have already asked this question on stackoverflow. Usually I check stackoverflow regularly for new question about mosby, but didn't yesterday ...

**Comment by Try4W** [comment]
I understood. Well, thanks again!
