### ISSUE TITLE
onAttach(Context context) for latest support lib

### ISSUE THREAD

**Issue by teamfunk** [sockeqwe/mosby#137]
Mosby is currently wiring up the lifecycle method onAttach(Activity activity) in MvpFragment / FragmentMvpDelegate. As onAttach(Activity activity) is deprecated in the latest support fragment I would like to use the new onAttach(Context context) which seems not to be wired up in Mosby yet. Is there the possibility to include it in the lib? Maybe in a new release as maybe you don't want to break compatibility with older support lib versions?
For now i quickly moved several classes in my package and added the lifecycle method (including MvpInternalDelegate which i didn't have to modify but it is package protected)

Thanks for your nice library!

**Comment by sockeqwe** [comment]
Hm, what do you mean with `wiring up`?

`onAttach()` is delegated to the delegate, but it does nothing, so everything should still work as expected ... https://github.com/sockeqwe/mosby/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/delegate/FragmentMvpDelegateImpl.java#L100

**Comment by teamfunk** [comment]
with wiring up i meant the delegation.
Ah i see its my fault. the normal presenter doesn't use onAttach at all and only hooks into onViewCreated and onViewDestroyed with attachView and detachView. I might run into a special case (video stuff) where  i maybe need to delegate more lifecycle methods to the a presenter but now i got how to do it. Hopefully i can prevent that - i know lifecycle in a presenter is not the best idea... This can be closed :-)

**Comment by sockeqwe** [comment]
Thanks for the clarification!

teamfunk <notifications@github.com> schrieb am Mi., 1. Juni 2016, 14:26:
