### ISSUE TITLE
Do we really need to write ViewState?

### ISSUE THREAD

**Issue by Try4W** [sockeqwe/mosby#138]
Can we let do this to code generator? :)

I found this library: https://github.com/Arello-Mobile/Moxy
And there is implemented an interesting idea. `ViewState` is automatically generated.
There is a queue of commands sent to `View`. You can also apply different `ViewStateStrategies` to different `View's methods`. Like: apply only last one after re-attaching, clean all other commands and apply this one. Look at the gif and sample app to see what I mean.

By simply applying strategies to `View's methods` we can forget about writing `ViewStates` at all. Would be nice to see some "ViewStateGenerator" extension for Mosby 3.0.

**Comment by sockeqwe** [comment]
Are you suing RxJava?

**Comment by Try4W** [comment]
Yep.

**Comment by vkiyako** [comment]
It's sometimes very implicit. You can easily make a mistake if you queue a command that shows some animation or an error which is already resolved and so on

**Comment by sockeqwe** [comment]
Consider using Model-View-Intent (MVI) module; sample is also available. Pre release (alpha release of Mosby `3.0.0-alpha1` containing MVI module) coming soon.
