### ISSUE TITLE
Add support for DialogFragment

### ISSUE THREAD

**Issue by fahimk** [sockeqwe/mosby#14]
It's almost exactly the same as regular Fragment, I'm not sure if there is an easy way to share the boilerplate code between them.

If anyone does try to add support for DialogFragments, this will keep the dialog on the screen for orientation changes.

```
    @Override
    public void onDestroyView() {
        if (getDialog() != null && getRetainInstance()) {
            getDialog().setDismissMessage(null);
        }
        ButterKnife.reset(this);
        super.onDestroyView();
    }```

**Comment by sockeqwe** [comment]
I will have a look at `DialogFragment`. I guess it's just a copy & paste from already existing `MvpFragment` implementation

**Comment by fahimk** [comment]
Yea, that's what I've done in my current project.

**Comment by jenzz** [comment]
I've been experimenting with this library a tiny bit this afternoon and was looking for a similiar `PreferenceFragment` implementation.

I think the best and most flexible solution for this is a delegate interface / abstraction similar to what we can find in the [latest support library update](https://android.googlesource.com/platform/development/+/master/samples/Support7Demos/src/com/example/android/supportv7/app/AppCompatPreferenceActivity.java). So I would expect this library to provide abstract MVP implementations for the most common base classes, but if I cannot find a particular implementation, I can still extend the support to any type of Activity, Fragment, etc that I'm looking for.

**Comment by sockeqwe** [comment]
Yep, actually, the ViewState implementation already works like that by providing a delegate. Have a look at `ViewStateManager` and  `ViewStateSupport`. Maybe I should rename `ViewStateManager` to something like `ViewStateDelegate` and rename methods  to match activity / fragments lifecycle names to make it more clear how to use them.

**Comment by IgorGanapolsky** [comment]
Yes, please rename to make them more clear with the design pattern.

Igor

**Comment by sockeqwe** [comment]
I have written a new blog post which describes how to use the delegate. 
http://hannesdorfmann.com/android/mosby-playbook/

See "Tip 22" (scroll down to the end of the page)

**Comment by siavashabdoli** [comment]
@sockeqwe  your blog page show 404 error :D is there any example for dialogfragment in your project?

**Comment by sockeqwe** [comment]
@siavashabdoli I have updated the linke: http://hannesdorfmann.com/android/mosby-playbook 
No there i no example project, but dialogfragments doesn't behave differently than any other fragment.

**Comment by siavashabdoli** [comment]
@sockeqwe  Yes, I see but we can't extend your library class directly in this one. I have to implement MvpViewStateDelegateCallback and implement attaching detaching and all MVP logic, is it right?

**Comment by SuperThomasLab** [comment]
@sockeqwe I read your blog post and understand how to use the delegate. However, your example code for a DialogFragment uses a custom view. Where should I call the `delegate.onViewCreated(View, Bundle)` method if I'm overriding `onCreateDialog(Bundle)` instead?

**Comment by liuzhen2008** [comment]
@sockeqwe I see that we use a MvpViewStateDelegateCallback in the document. Is this only available in mosby3?

**Comment by sockeqwe** [comment]
@SuperThomasLab 
sorry, I have missed your comment / question, somehow I have accidentally muted this thread. 
I think it works if you just use `onCreateDialog(Bundle)` for the dialog title etc. `onCreateView(...)` for your main custom view.  I have never tried it.
 
@liuzhen2008  it might have been renamed in Mosby3 (or moved into another package, but it there is the same class also in Mosby 2 (and Mosby 1).

I have to update the docs #185

**Comment by liuzhen2008** [comment]
@sockeqwe Any idea what the name is in mosby2? 

I see BaseMvpDelegateCallback or FragmentMvpDelegate. Is this it?

**Comment by sockeqwe** [comment]
I think it was `MvpViewStateDelegateCallback ` (must be implemented by your Fragment or Activity) `ActivityMvpViewStateDelegateImpl` and `FragmentMvpViewStateDelegateImpl` where you have to forward (delegate) the lifecycle events to.

**Comment by mseroczynski** [comment]
@sockeqwe Are you planning on adding base implementations for DialogFragment or should it be handled by developer by design?

**Comment by sockeqwe** [comment]
Not planned to add a DialogFragment base implementation for MVP, MVP ViewState and MVI (mainly because of time constraints) but if such a base implementation is that straight forward as it is with any other Fragment (just adding the corresponding delegate) then we can add it to this library. 

Do you wanna send a pull request?

**Comment by mseroczynski** [comment]
If I'll manage to implement it I'll surely make a PR, but currently (sadly) I just need a fast working solution for my specific MVP case for my work so please do not consider it 'incoming asap' :). Btw, big thanks(!) for your work with Mosby, awesome blog posts, The Context podcast and everything! 👍

**Comment by sockeqwe** [comment]
Thank you very much!

If you use traditional Fragment lifecycle callbacks and setup your Dialog's view in `Fragment.onCreateView()` I would expect that simply adding the delegate like I did [here](https://github.com/sockeqwe/mosby/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby3/mvp/MvpFragment.java) works.

**Comment by ltrojanowski** [comment]
I'm not sure if it is a good idea to even add this to mosby. It's yet another thing to maintain and I can't imagine how busy someone like @sockeqwe must be anyways. The suggested solution of adding the delegate worked with no problems. If anyone stumbles upon this and wants to copy paste an implementation for MVI check out this [gist](https://gist.github.com/ltrojanowski/ae35b040cf1c149097a41959d08aef0a).
