### ISSUE TITLE
onNewViewState called too early

### ISSUE THREAD

**Issue by Try4W** [sockeqwe/mosby#145]
Now I can call presenter like that to update UI at the first time:

    @Override
    public void onNewViewStateInstance() {
        presenter.initialize();
    }

in `Presenter`:

    @Override
    public void initialize() {
        getView().setColor(projectManager.getProject().getColor());
        getView().setEditMenuItemEnabled(projectManager.getProject().isOpened());
    }

And I always must wrap code with `Handler.post` to avoid executing this code _before_ `Views` is inflated.

    @Override
    public void setEditMenuItemEnabled(boolean enabled) {
        getViewState().setEditEnabled(enabled);
        handler.post(() -> {
            editMenuItem.setEnabled(enabled);
            ViewUtils.makeItLooksEnabled(editMenuItem.getIcon(), enabled);
        });
    }

It looks like `onNewViewState` called too early.

Additional info

    mosbyVersion = '2.0.1'
    androidBuildToolsVersion = "23.0.3"
    androidAppCompatVersion= "23.4.0"
    androidMinSdkVersion = 15
    androidTargetSdkVersion = 23
    androidCompileSdkVersion = 23

Tested on Android 6.0/Genymotion.

**Comment by sockeqwe** [comment]
I guess `editMenuItem` is a Toolbar / ActionBar Menu Item, right? 
`onNewViewState()` will be called after `Fragment.onViewCreated()`, so your xml layout will definitely be inflated.

But I'm not sure when xml menu will be inflated. Do you use plain Toolbar or do you set Toolbar as support action bar.

**Comment by Try4W** [comment]
`I guess editMenuItem is a Toolbar / ActionBar Menu Item, right?`

Yeah, it is a bad example with MenuItem. But NullPointerException also thrown when I trying to update typical View inflated by ButterKinfe. I will test this problem and write back in few days.

**Comment by Try4W** [comment]
`But I'm not sure when xml menu will be inflated.`

I think it inflated somewhere after `onCreateView`. I use support action bar.

**Comment by sockeqwe** [comment]
Ok, so ViewState will be instantiated in `Fragment.onActivityCreated()` as you can see here: 
https://github.com/sockeqwe/mosby/blob/master/viewstate/src/main/java/com/hannesdorfmann/mosby/mvp/delegate/FragmentMvpViewStateDelegateImpl.java#L51

https://github.com/sockeqwe/mosby/blob/master/viewstate/src/main/java/com/hannesdorfmann/mosby/mvp/delegate/MvpViewStateInternalDelegate.java#L116


According [this](https://github.com/xxv/android-lifecycle) lifecycle diagram, `Fragment.onActivityCreated()` will be called after `Fragment.onCreateView()` and after `Fragment.onViewCreated()`. So as long as you do your ButterKnife setup before `Fragment.onActivityCreated()` everything should be fine. 

Regarding MenuItems: Bad news, according to the same diagram, Menu inflation happens after `Fragment.onActivityCreated()` 

Not sure how to fix this properly.

**Comment by Try4W** [comment]
> But NullPointerException also thrown when I trying to update typical View inflated

There is my mistake. I used to inject additional `Views` to AppBarLayout from `onStart()`. Now I do it in `onCreateView()`.

    View toolbarPartView;

    EditText titleEditText;

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        toolbarPartView = getCustomizer().setExtendedToolbarView(R.layout.view_edit_project_toolbar_part);
        titleEditText = ButterKnife.findById(toolbarPartView, R.id.title_edit_text);
        return super.onCreateView(inflater, container, savedInstanceState);
    }

![image](https://cloud.githubusercontent.com/assets/5736157/16946223/16c0e7be-4db1-11e6-91df-64295debb0d9.png)

> this lifecycle diagram

Very helpful diagram, thanks.

> Not sure how to fix this properly, I think for now your workaround with a post() is the best option.

Yeah, it works for me. But I will try to use `Toolbar.inflateMenu()` as it looks more logical. Thanks again :)
