### ISSUE TITLE
Move lce package to separated library

### ISSUE THREAD

**Issue by Try4W** [sockeqwe/mosby#148]
Would be nice to move [lce](https://github.com/sockeqwe/mosby/tree/master/viewstate/src/main/java/com/hannesdorfmann/mosby/mvp/viewstate/lce) package to separated library. It looks like a good solution but I came up with my own. And now `lce` package looks like samples in `viewstate` library. It isn't critical but annoying.

**Comment by sockeqwe** [comment]
Moved into own module in upcoming `3.0` relases
