### ISSUE TITLE
Can I use the RxLifecycle library?

### ISSUE THREAD

**Issue by leesunghyun** [sockeqwe/mosby#151]
Hi. 
Can I use the RxLifecycle from a class that inherits MvpActivity and MvpBasePresenter?

https://github.com/trello/RxLifecycle

**Comment by vanniktech** [comment]
Of course you can because both provide delegates.

Once I get around to extended mosby components - #143 - I also wanted to add RxLifecycle suport

**Comment by sockeqwe** [comment]
basically yes, since both libraries are following the delegation principle, but you should not intersect both responsibilities. i.e. don't call `createPresenter()` from a RxLifecycle event, since it is already managed by mosby.
