### ISSUE TITLE
Sample Mail... Scroll in Background if Menu is open

### ISSUE THREAD

**Issue by HowardSchmaeu** [sockeqwe/mosby#160]
is there any Idea why the Mail List is scrolling if i scroll in the open Menu and how can i fix this??

Thank you
Howard

**Comment by sockeqwe** [comment]
Funny, I answered a similar question last week:

https://www.reddit.com/r/androiddev/comments/51sb0e/conductor_and_mvp_how_should_it_be_done/d7fdhmq

hope that helps

**Comment by HowardSchmaeu** [comment]
sorry that i open it again... i saw your answer on reddit... but what can i do to avoid this behavior in the Mail Sample?? i try setting     
```
android:clickable="true"
android:isScrollContainer="true"
```

but it still scrolls also the background... i understand something wrong and this is not going to work on a drawer??
