### ISSUE TITLE
An alternative integration with Mosby: AndroidAnnotations & Bolts

### ISSUE THREAD

**Issue by deisler84** [sockeqwe/mosby#163]
Hi sockeqwe, thanks for great MVP framework, I try to play for awhile with Mosby and find it suitable for my Android projects but just have a question regarding integration of Mosby with other libraries.

I can see Mosby is more friendly to be integrated with Butterknife & RxJava, but I personally is getting used with [AndroidAnnotations](https://github.com/excilys/androidannotations) for view binding and [Bolts](https://github.com/BoltsFramework/Bolts-Android) for asynchronous work. Can I have advice as if those two libraries can integrate with Mosby without any pain ?

Thanks,

**Comment by sockeqwe** [comment]
Yes this should be possible, but I never tried both libraries before.

AndroidAnnotations should work. Just try to annotate your `Activity extends MvpActivity` with `@EActivity` etc. 

Alernatively, if AndroidAnnotation for some strange reasons disallow to extend from `MvpActivity` you can try the following:

Mosby follows the composition over inheritance principle by providing a delegate.
See the docs http://hannesdorfmann.com/mosby/viewstate/ (scroll down until ViewState Delegate section). So basically you have to "forward"  all lifecycle event to Mosby's `ActivityDelegate` or `FragmentDelegate`, see https://github.com/sockeqwe/mosby/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/MvpActivity.java

In addition you also have to implement `ActivityMvpDelegateCallback`or `FragmentMvpDelegateCallback`

Regarding Bolts library:
I can't see any reason why Bolts wont work with Mosby. Just keep in mind to cancel tasks in `presenter.detachView(false)` (parameter false means that the presenter should be destroyed permanently so some cleanup should be done here, like canceling tasks).
