### ISSUE TITLE
crash question

### ISSUE THREAD

**Issue by siavashabdoli** [sockeqwe/mosby#165]
I get this error on crashlytics panel:
Fatal Exception: java.lang.NoSuchMethodError
android.support.v4.app.FragmentActivity.isChangingConfigurations
com.hannesdorfmann.mosby.mvp.MvpFragment.shouldInstanceBeRetained (MvpFragment.java:91)
com.hannesdorfmann.mosby.mvp.delegate.MvpInternalDelegate.detachView (MvpInternalDelegate.java:70)
com.hannesdorfmann.mosby.mvp.delegate.FragmentMvpDelegateImpl.onDestroyView (FragmentMvpDelegateImpl.java:73)
com.hannesdorfmann.mosby.mvp.MvpFragment.onDestroyView (MvpFragment.java:106)
com.hannesdorfmann.mosby.mvp.MvpFragment.shouldInstanceBeRetained (MvpFragment.java:91)

I override your manifest for library to use it with api 10 and I already test it on android 2.3.3 and it was working ok! but now I see this crash on crashlytics. Hi I can fix this for my version? is crash related to api 10? because the method is for support v4 library so I can't understand why this occurred.

**Comment by sockeqwe** [comment]
Hi,
yes the method `isChangingConfigurations()` has been introduced with API 11:
https://developer.android.com/reference/android/app/Activity.html#isChangingConfigurations()

as part of the`android.app.Activity` class (and not as part `android.support.v4.app.FragmentActivity`, but `FragmentActivity extends Activity`).


Hence, this won't work on API < 11.

You could implement `isChangingConfigurations()`  in your Activity and either call
`super.isChangingConfigurations()` if API >=11 or implement your own thing  if (API < 11). You may want to take a look at Activities source code, but I'm not sure how  this could be back ported. https://github.com/android/platform_frameworks_base/blob/master/core/java/android/app/Activity.java#L5152


You could try to just return `false` if API < 11 . That would mean that the View's state (and Presenter) will not survive screen orientation changes. DISCLAIMER: That might also cause some other unwanted side effects I'm not aware of right now.
