### ISSUE TITLE
[Question] How to save LCE view state using MvpLceActivity?

### ISSUE THREAD

**Issue by fzymek** [sockeqwe/mosby#166]
Hello,

I am trying out mosby, and I have trouble implementing saving view state for lce view when using activity. 

I tried creating custom view which implements both `RestorableViewState` and `LceViewState` and return this view `createViewState`. I've also implemented `apply` method but with device rotation view state was not saved and mosby was calling `showLoading` without caling `loadData`. 

Is it even possible to use `LCEViewState` with activites?

**Comment by sockeqwe** [comment]
Sure, it is possible with Mosby. If you call
MvpActiviy.setRetainInstancestate(true) in onCreate() you dont even have to
use a RestireableViewState. Can you share some of your code?

Filip Zymek <notifications@github.com> schrieb am Fr., 30. Sep. 2016, 12:06:

**Comment by fzymek** [comment]
Ok, I got it working with calling `setRetainInstance(true)` in my activity and using `RetainingLceViewState` as my `ViewState`.

Thanks!
