### ISSUE TITLE
Problem with  gradle:1.2.0-beta1

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#17]
Hello,
I see in your project's build.gradle file you are using dependency `classpath 'com.android.tools.build:gradle:1.2.0-beta1'`.  However, that does not work in Android Studio 1.2 RC 3 - the project does not build when I import it, and I cannot run any of the module samples.  The only way I was able to fix this problem is to revert back to
`classpath 'com.android.tools.build:gradle:1.1.3'`

Please explain why you are trying to use **gradle:1.2.0-beta1** in the mosby project?

Thank you,
Igor

**Comment by sockeqwe** [comment]
Hi, 
the reason i use **1.2.0-beta1** is for better support for unit testing, because of  **1.2.0** the generated  `R.java` is shared with plain old unit testing  (folder `test` and not `androidTest`).

However, you can simply use `1.1.3` as lang as you don't run the unit test (some unit test features that require `1.2` I have not pushed to master yet).


By the way: I'm using Android Studio Android Studio 1.2 RC 3 and **1.2.0-beta1** without facing any kind of problems.

Are you sure that your issue is not related to #10

**Comment by IgorGanapolsky** [comment]
I don't think it's the same issue, because I am not seeing explicit errors.  In my case, the green play button never gets enabled because the modules aren't built into android applications.

**Comment by sockeqwe** [comment]
Hm, really strange ... 
Now I'm facing the problem that I can only build the samples by enabling `Android Instrumentation Tests` in Android Studio and not `Unit Tests`. I'm afraid, but I will have to update to android gradle plugin  1.2.0-beta1 with one of my next commits. Could you once more try to pull the latest master branch and to switch to 1.2.0-beta1?

**Comment by sockeqwe** [comment]
Oh I think you have to enable unit test in android studio:
http://tools.android.com/tech-docs/unit-testing-support

Enable the unit testing feature in Settings > Gradle > Experimental.

I guess that is the problem you face with `1.2.0-beta1`

**Comment by IgorGanapolsky** [comment]
I do not see **unit testing feature** in Settings > Gradle > Experimental

**Comment by sockeqwe** [comment]
Me neither. The site is refering to android studio 1.1 which is based on intellij 13 . I guess things has changed in android studio 1.2 (based on intellij 14) or removed completely. I can't find this option  anymore. Nevermind ...

**Comment by IgorGanapolsky** [comment]
I am now seeing this error in Android Studio gradle message at the bottom:
> A newer version of com.android.tools.build:gradle than 1.2.0-beta1 is available: 1.2.0

**Comment by IgorGanapolsky** [comment]
Did a pull request for 1.2.0, works now!

**Comment by sockeqwe** [comment]
Hm, now it's my android studio that mark any dependency to support v4 as unknown. However, pressing the play button can compile and run the whole things expected ... Come on google ... what's going on ...

**Comment by IgorGanapolsky** [comment]
Do you even need support v4?  Maybe you can just get away with v7 :wink:
