### ISSUE TITLE
Manage LifeCycle

### ISSUE THREAD

**Issue by tux-world** [sockeqwe/mosby#171]
implemented some features like with `lightCycle` by default? we don't need to implementing that Handy or using LightCycle?

**Comment by sockeqwe** [comment]
Why not using lightcycle?

**Comment by tux-world** [comment]
because on this [link](http://hannesdorfmann.com/android/presenters-dont-need-lifecycle) as far as i know this library we don't need to implementing that

**Comment by sockeqwe** [comment]
I'm not sure if I understood what you are asking for. What would you like to add to mosby and why?

**Comment by tux-world** [comment]
I'm using classic MVP on android and i would like to use your library, and i'm managing lifeCycle normally, my code is like with spaghetti code

**Comment by stavfx** [comment]
@tux-world, try reading http://hannesdorfmann.com/android/presenters-dont-need-lifecycle
