### ISSUE TITLE
Let change or remove showContent animation in LCE views

### ISSUE THREAD

**Issue by urizev** [sockeqwe/mosby#173]
Hi,

I think it is not possible right now to remove or change showContent animation in, for instance, MvpLceFragment (and subclasses).

I know a solution would be to override pertinent methods but I think it would be better if animation where decoupled from current implementation.

I think it wouldn't be hard to implement.

**Comment by sockeqwe** [comment]
You can override `animateContentViewIn()`
https://github.com/sockeqwe/mosby/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/lce/MvpLceActivity.java#L112

**Comment by urizev** [comment]
That's right! I missed that :(

Thanks! And sorry for the obvious question
