### ISSUE TITLE
Using a class from your project in my open source project

### ISSUE THREAD

**Issue by athkalia** [sockeqwe/mosby#174]
Hello,

do you mind if I use the snapshot v3.0 version of com.example.mvp.MvpNullObjectBasePresenter
in one of my open source projects? It's going to be a template project that uses the usual MVP with mosby, RxJava, Dagger 2 etc.

**Comment by sockeqwe** [comment]
Sure, go ahead! Thanks for asking! Please post the link once published,
would love to learn from you / see how you use it

Sakis Kaliakoudas <notifications@github.com> schrieb am So., 13. Nov. 2016,
14:48:

**Comment by athkalia** [comment]
Will do : >
thanks

**Comment by athkalia** [comment]
Hey pal, I just released that project I was talking about:
https://www.reddit.com/r/androiddev/comments/5thahs/open_source_android_app_with_loads_of_goodies_and/

Looking forward to your feedback : >

**Comment by sockeqwe** [comment]
Thanks for coming back! I will take a look this week!

Sakis Kaliakoudas <notifications@github.com> schrieb am So., 12. Feb. 2017,
15:18:
