### ISSUE TITLE
Mail Sample Error

### ISSUE THREAD

**Issue by rkrater** [sockeqwe/mosby#176]
While try to build the mail sample I get this error: 

app/src/main/java/com/hannesdorfmann/mosby/sample/mail/statistics/StatisticsDialog.java
Error:(21, 45) error: cannot find symbol class MvpViewStateDelegateCallback

**Comment by sockeqwe** [comment]
Hm ... Thanks for reporting, i will take a look tomorrow

Rob Krater <notifications@github.com> schrieb am Do., 17. Nov. 2016, 21:32:

**Comment by sockeqwe** [comment]
Hi,
I'am not able to reproduce this issue. 
The sample mail app compiles without any issues with the current master branch.

**Comment by rkrater** [comment]
I created a new android studio project then copied in the sample mail project contents. I replaced compile project(':viewstate') with compile 'com.hannesdorfmann.mosby:mvp:2.0.1' & compile 'com.hannesdorfmann.mosby:viewstate:2.0.1'

**Comment by sockeqwe** [comment]
The current master branch contains the upcoming major 3.0 version. This class was named differently in 2.x version. I have to dive into the git log to get the Version 2.0 name .

Meanwhile you could also use the 3.0.0-SNAPSHOT version
