### ISSUE TITLE
ClassCastException ... i'm SURE it's my fault ... but i don't know why :-)

### ISSUE THREAD

**Issue by HowardSchmaeu** [sockeqwe/mosby#177]
Hi Hannes, 

sorry for disturbing u :-) 
but I've set up a new small MVP Project and get this error when my App is going in Background. I don't get it ... what can be wrong? I've used ArrayList's several times in another projects ... on the same way ... without any error... did you have any idea where I've to looking for?? 

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to android.os.Parcelable
at com.hannesdorfmann.mosby.mvp.viewstate.lce.data.ParcelableDataLceViewState.writeToParcel
```

**Comment by sockeqwe** [comment]
Hi, 
you are using the wrong ViewState Type I guess. Are you using `ParcelableDataLceViewState`? If your "data" is an array list you better use `ArrayListLceViewState` or `CastedArrayListLceViewState`

**Comment by HowardSchmaeu** [comment]
sorry for this late response... but YES it works now... THX
