### ISSUE TITLE
Forced IDs

### ISSUE THREAD

**Issue by Dragas** [sockeqwe/mosby#183]
Why force particular elements in every fragment match particular IDs? 
Instead, shouldn't the implementation of `MvpLceFragment` set those particular elements regardless of their IDs via such methods as `setErrorView`, `setContentView` and such? 
In my opinion, implementation wouldn't be so forced and you could use entire layouts for errors, instead of just `TextView` and still retain the `LceAnimator` functionality.

**Comment by sockeqwe** [comment]
View id's are configureable in upcoming  `3.0`. you can override `createLoadingView()` , `createErrorVIew()` and `createContentView()`. You are still forced to use `TextView` for errorView.

See the thing is `MvpLceFragment` is tailored for a very specific use case. If you have different requirements then you should write your own implementation and not use `MvpLceFragment`
