### ISSUE TITLE
MVI: Find better name for setRestoreViewState(boolean)

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#184]
Find a more generic name for `MviDelegateCallback.setRestoreViewState()` because "ViewState" might not be the correct term.

**Comment by charbgr** [comment]
What about `shouldViewStateBeRestored(Boolean)` or even more explicit method names like `restoreViewState()`, `alwaysRecreateViewState`

**Comment by sockeqwe** [comment]
Sorry, this was a little bit misleading (and I haven't provided any real explination).
Basically, Mosby internally calls `MviActivity.setRestoreViewState(true)` and  `MviActivity.setRestoreViewState(false)` to inform the Activity that `MviActivity.render(model)` method might be invoked because the view gets reattached like this:

```java
class MyActivity extends MviActivity {
  private boolean restoreViewState;

  @Override 
  public void setRestoreViewState(boolean b) {
     this.restoreViewState = b;
  }

  @Override
  public void render(MyModel model) {
      if (restoreViewState){
          // render slightly different (i.e. don't run animations)
      } else { 
        // render as usual
      }
    }
}
```

The only real use case I can think of is to NOT to run some animations when reattaching the view (i.e. after screen orientation change).

The question of this issue is that: `setRestoreViewState()` might not be a good name because of `ViewState` in the name. I'm not sure how people will name their model classes

**Comment by charbgr** [comment]
Hmm.. Is `ViewState` the correct name? If we say that we need to render a model for the view, is `ViewModel` the correct name? Actually, a `ViewModel` represents the state of the View.

Although, if we change the name to `ViewModel`, there will be confusions with MVVM pattern.

What if this boolean came as an argument on the `render` method? Like `render(MyModel model, boolean isViewStateRestored)` ?

**Comment by TobiasRe** [comment]
For my project I'm naming the classes `ViewModel` instead of `ViewState`, because the model includes the state. My `ViewModel` classes include a property that reads the state, for easier debugging / state checks.
I put a facade on top of MviView / MviActivity so I can define my interface like.
```Java
abstract class BaseActivity extends MviActivity {
  private boolean restoreViewState;
  
  abstract protected void render(ViewModel model, boolean isRestored);

  @Override 
  public void setRestoreViewState(boolean b) {
     this.restoreViewState = b;
  }

  @Override
  public void render(ViewModel model) {
     this.render(model, this.restoreViewState)
    }
}
```

**Comment by sockeqwe** [comment]
What about calling this method just `setRestoreState(boolean)` ... just a generic / general name

**Comment by charbgr** [comment]
Why do you want to keep `setRestoreState(boolean)` and not give this boolean on the `render` method? In case someone wants a more sophisticated logic on `setRestoreState(boolean) ?

**Comment by sockeqwe** [comment]
Because the render method is called from presenter, but the presenter has
no knowledge whether or not render() by i.e. screen orientation change

Vasilis Charalampakis <notifications@github.com> schrieb am Do., 9. Feb.
2017, 17:07:

**Comment by charbgr** [comment]
Ok, I see.

As Mosby has a domain object `ViewState`, `setRestoreViewState(boolean)` seems the most appropriate term.
