### ISSUE TITLE
Should MviPresenter offer getViewStateObservable() or not?

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#186]
The idea of `MviPresenter.getViewStateObservable()` is that another MVI UI component could use this observable as "intent" for rendering it's own view state.

i.e: AView has APresenter. BView has BPresenter that takes `APresenter.getViewStateObservable()` as input (i.e. as intent) to coordinate `BView`. In other words: Changing `AView` has impact to what `BView` displays. 

However, I think that usually both UI components should rather "observe" both the same "model" from business logic. Offering `getViewStateObservable()` may lead to the wrong impression that `getViewStateObservable()` should be used everywhere. Actually, I think that there are only very few edge cases where using `MviPresenter.getViewStateObservable()` makes sense and should be preferred over "observing the same model". 

Furthermore, parent - child relations are not a good idea and `MviPresenter.getViewStateObserable()` allows you to build such parent-child relations (attention: cycles in your dependency graph).

As compromise we could move `getViewStateObservable()` to `MviBasePresenter` (rather than `MviPresenter` and make `getViewStateObservable()` protected. 

By doing so a developer explicitly has to override `getViewStateObservable()` with `public` visibility  in his own presenter to make `getViewStateObservable()` visible for other presenters (to establish a child-parent relationship).

Note: child-parent relation may not be the correct word because there is no `Presenter.getParentPresenter()` method etc. so that is not really a parent - child relation from a hierarchical point of view, but I hope you get what I'm trying to say with "parent-child" relation.

**Comment by FabianShallari** [comment]
Decoupled communication between UI components/presenters can be achieved as you have correctly mentioned by pushing it down to the business logic layer (best approach) or by using publish subjects (which in this case would act as a specialized one-channel event bus). 

I think that exposing viewState changes of one particular component so that other components (Views, Presenters) can react to that is 99% of the time a code smell and a library should make it hard for its users to be able to create that kind of code. 

1% of cases which depend on this kind of behavior should be encouraged to push the logic down and keep their UI/presenter flows decoupled and isolated from each other.

**Comment by sockeqwe** [comment]
Thanks for your feedback. I think you are right. At the moment I tend to make the visibility of `getViewStateObservable()` protected, so that in the 1% of cases you can make this public.

What do you think about that?

**Comment by FabianShallari** [comment]
My opinion is neutral in that. Personally in my code if I am lazy to push the state down to the business logic and observe it there, I use a `PublishSubject`or a `PublishRelay` and inject it to the components (or make it available as a lazy static singleton) that are interested in observing/notifying therefore kind of emulating an `EventBus`. 

I still have to run into use cases where I need to change `BView` by referencing `AView`s state directly so maybe my perspective is not the most helpful in this case. Theoretically you are kind of breaking encapsulation by exposing it so maybe not the best approach there 😕  

Anybody else knows of any good use case when you need to expose it that cannot be achieved via `EventBus, PublishSubject, Observable Business Logic`?.

**Comment by charbgr** [comment]
I think playing with visibility is the most appropriate solution. 
In case someone wants, something like `two-way binding` technique, he will make it public, no?

**Comment by sockeqwe** [comment]
I think it is the best to use the visibility modifier "workaround" to be flexible enough for any further use cases we havent thought about yet. 

Thank you all for your input! Really appreciated!

**Comment by sockeqwe** [comment]
I have changed mind : `getViewStateObservable()` has public visibility in upcoming `3.0` release. 

Mainly for unit testing reasons:
now you can simply write unit tests for presenter by accessing the presenters observable which makes unit testing more convenient.

**Comment by sockeqwe** [comment]
oops, forgot to update this:

Finally I have changed mind again: `getViewStateObservable()` has `protected` visibility in `3.0`.

Testing can be done easily even without `getViewStateObservable()`
