### ISSUE TITLE
mosby3:mvi SNAPSHOT failed to resolve 'presentermanager'.

### ISSUE THREAD

**Issue by yatatsu** [sockeqwe/mosby#188]
I tried mosby3 at **3.0.0-SNAPSHOT** (8fe20be) version, but dependencies missed.

I think this is minimal usage in `app/build.gradle`

```build.gradle
dependencies {
  compile 'com.hannesdorfmann.mosby3:mvi:3.0.0-SNAPSHOT'
}
```

But I got this message.

```
Failed to resolve: com.hannesdorfmann.mosby3:presentermanager:3.0.0-SNAPSHOT
```

and I cannot find that module at [repository](https://oss.sonatype.org/content/repositories/snapshots/com/hannesdorfmann/mosby3/).

Is it still not released or my usage is wrong? Thanks.

**Comment by sockeqwe** [comment]
Indeed, something went wrong while uploading this artifact. I have pubished that now again. Should work now. Thanks for reporting!

**Comment by Burtsev-Ivan** [comment]
Failed to resolve: com.hannesdorfmann.mosby3:mvi:3.1.2-SNAPSHOT
