### ISSUE TITLE
MVI: Presenter.unbindIntents() called more than once for MviActivity

### ISSUE THREAD

**Issue by kibao** [sockeqwe/mosby#191]
Steps to reproduce:
- open app
- click system home button
- go back to the app through recent apps
- click system home button again

**Comment by sockeqwe** [comment]
Do you use a Fragment? Activity? or ViewGroup? Or is it reproducible in the sample application?

**Comment by kibao** [comment]
I use MviActivity and didn't try to reproduce in the sample applicaiton, because only `ProductDetailsActivity` extends `MviActivity`.

I've just tested with clean project with classes listed below and when I leave the app, go back to the app few times, logcat shows only one `bindIntents` and many `unbindIntents`.

**MainActivity.java**
```
public class MainActivity extends MviActivity<MainView, MainPresenter> {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @NonNull
    @Override
    public MainPresenter createPresenter() {
        return new MainPresenter();
    }
}
```

**MainPresenter.java**
```
public class MainPresenter extends MviBasePresenter<MainView, MainView.ViewState> {
    @Override
    protected void bindIntents() {
        Log.d("MainPresenter", "bindIntents");
    }

    @Override
    protected void unbindIntents() {
        Log.d("MainPresenter", "unbindIntents");
    }
}
```

**MainPresenter.java**
```
interface MainView extends MvpView {
    class ViewState {
    }
}
```

**Comment by sockeqwe** [comment]
Yes, this is a bug, thanks for reporting!
