### ISSUE TITLE
Reuse view in MVP

### ISSUE THREAD

**Issue by exotfboy** [sockeqwe/mosby#192]
I am woring on an Android video application, and I found mosby is awesoome as a MVP library.

And I have two activities at the moment the `HomeActivity` which display the videos(can be sorted by time,popular and etc) and the favorates.

The `PlayActivity` which display the detailed information of the selected video, also it will display the recommendted vidoes for the current video.

Screeshot:

![image](https://cloud.githubusercontent.com/assets/16457917/22019467/add6d402-dcee-11e6-9e6d-bd38d4f940a1.png)

Now for the `HomeActivity` I use the `ViewPager` to display three `Fragment`:

- VideoListFragment(for displaying vidoes online and sort them by different condition)
- VideoListFragment(for displaying vidoes favorated by the user)

When use click the item in the `ListView`, `PlayActivity` should be activated, almost all of them have the same behavior.

I tried to make the `VideoListFragment` extends `MvpLceFragment`, and create a presenter named 'VideoListPresenter` which will load vidoes online.

However for the second `VideoListFragment` which have almost the same UI only with different videos(from local database), I wonder if I can reuse some logic. And I found that it is the `VideoListFragment` who create the `presenter` instance. So I can not reuse the `VideoListFragment` here.

Also in the `PlayActivity` there is also a ListView for recommended videos, I want to reuse that too.

In a word, three `ListView` with the same UI with different data, how to use the MVP in this case?

**Comment by sockeqwe** [comment]
Use inheritance, i.e. `LocalDatabaseVideoListFragment extends VideoListFragment` and then override the createPresenter method.
