### ISSUE TITLE
Should we use anoyher name for MviPresenter?

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#193]
Since MviPresenter is not a "traditional" presenter, we should consider use another name. Maybe something like `MviBinder` or `MviCoordinator`.

On the other hand `MviPresenter` does make sense since it can be used with traditional view oresenting calls like `view.showLoading()` instead of just one single `view.render(model)` method (Mosby doesn't force you to choose one or the other approach) .

Also we may have a `PresentationModel` which holds some View only properties like if an item in a list is selected or not, which is another good reason to name it `MviPresenter`.

What are your thoughts?

**Comment by sockeqwe** [comment]
We will stick with the name `MviPresenter`

**Comment by charbgr** [comment]
I also agree with this MviPresenter. `Coordinator` would be a little confused term if someone uses Square's [coordinators](https://github.com/square/coordinators).
