### ISSUE TITLE
selectCategory stops working  in 3.0 mvi sample app after leaving app

### ISSUE THREAD

**Issue by TobiasRe** [sockeqwe/mosby#199]
The navigation in the menu stops working in the mvi sample app after following procedure: 

1. Run the sample app
2. Select a category from menu
3. leave the app with a back press
4. return to the app (using recent apps)
5. trying to select a new category

**Comment by sockeqwe** [comment]
Thanks for Reporting, I will take a look. I guess it is just a bug in the
sample app.

To Re <notifications@github.com> schrieb am Di., 31. Jan. 2017, 15:57:
