### ISSUE TITLE
Could Mosby be utilized with viewpager?

### ISSUE THREAD

**Issue by javajack** [sockeqwe/mosby#2]
Thanks for awesome helper library and even more awesome blog post explaining the LCE pattern. It surely reflects the experience of 3 years digested into one well thought out library ! 

Your current examples are focused around displaying a lists ( they are common ), in general it is hard for android newbies to wrap their head around viewpager best practices.

Can you create a sample in your repo with dagger1,retrofit,lce that utilizes LCE pattern with view pager ?
--> "A layout that would have pull to refresh functionality and a view pager with one member displayed at at time instead of list..."" <--

For you it might be trivial task being a Mosby author but for others like me it would be a valuable starting point to pickup Mosby with viewpager !

**Comment by sockeqwe** [comment]
I can do that.
I'm not sure what exactly you mean with:

 >  one member displayed at time instead of list...

The view pager should display fragments containing a ListView with pull to refresh support, right?

**Comment by javajack** [comment]
List comes nowhere in picture, actually.
A pull to refresh layout with viewpager with adapter. Each time the pull to refresh is done, the adapter data is refreshed.

Each time the pull to refresh is done, the viewpager data would be refreshed by calling an API,
And =viewpager page would display one item at a time.

I would request you to build the example upon following third party API,

See following free API, it returns motivational news items at givesmehope.com
http://api.givesmehope.com/

Out viewpager exmaple would consume the response and display news items in a viewpager leveraging  Mosby framework , one news item at a time.

http://api.givesmehope.com/v1/posts/all.json?page=1

Grab "headline" and "image_src" from json responses to display in viewpager.

**Comment by sockeqwe** [comment]
So the swiperefreshlayout should refresh the view pager?

**Comment by javajack** [comment]
Yup, swiperefreshlayout  should refresh the pager !

**Comment by sockeqwe** [comment]
ok, pretty strange app navigation, but here it is:

https://github.com/sockeqwe/MosbyViewPagerDemo

Took about 20 minutes to code it thanks to mosby and some annotation processors.

Btw. I expect from you that you offer me a beer whenever you see me next time for doing your job ;) 
:beers:

**Comment by javajack** [comment]
Come over to Mumbai/India buddy, I'll host you with authentic Indian curries and sweets  :)

**Comment by javajack** [comment]
Your comment "pretty strange app navigation" is legit and the culprit is swiprefreshlayout mechanism.
The layout is so sensitive that is breaks letft/right swipe UX of viewpager.

http://stackoverflow.com/questions/25978462/swiperefreshlayout-viewpager-limit-horizontal-scroll-only

The solution is there in the answers , but I'm curious where that fits into mosby framework code base for applying that solution.

**Comment by sockeqwe** [comment]
it's not mosby related at all, so yes,  why not?

**Comment by javajack** [comment]
Ok tested the following solution, and it has improved the pager swipe. 
Pull to refresh works as expected.

http://stackoverflow.com/a/27934705/861454
