### ISSUE TITLE
pullToRefresh on error?

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#21]
Hi,
why do you have the `pullToRefresh` parameter in ErrorMessageDeterminer here: 
https://github.com/sockeqwe/mosby/blob/master/sample-dagger2-rx/src/main/java/com/hannesdorfmann/mosby/sample/dagger2/model/ErrorMessageDeterminer.java#L10

**Comment by sockeqwe** [comment]
Thanks, that is missing. I have to add that.

The idea was to display different kind of error message depending on pull to refresh or not pull to refresh.

i.e.

The `TextView` that displays an error message (pullToRefresh == false) should show that kind of message:
 > An error has occurred. Please click here to retry.

And you can click on the error view to retry.

If error was on pull to refresh, then the error is displayed as toast, where "Please click to retry doesn't make sense and therefor only
 > An error has occurred

should be displayed as toast message
