### ISSUE TITLE
MVI - RestoreViewOnCreateController equivalent

### ISSUE THREAD

**Issue by MFlisar** [sockeqwe/mosby#211]
Additonal to following:

    public abstract class MviController<V extends MvpView, P extends MviPresenter<V, ?>> extends Controller implements MvpView, MviConductorDelegateCallback<V, P>

will you add a version that extends `RestoreViewOnCreateController`?

**Comment by sockeqwe** [comment]
Yes, thats easy, i will add that one too.

Btw. Please report mosby-conductor related issues in mosby-conductor repo / issue tracker

https://github.com/sockeqwe/mosby-conductor/issues

**Comment by MFlisar** [comment]
Sure, just forgot that it's another repo

**Comment by sockeqwe** [comment]
No problem! Btw. the code from above is exactly how  it should look like.
Do you wanna send a pull request? Then a snapshot version will be build
automatically

MFlisar <notifications@github.com> schrieb am So., 12. Feb. 2017, 12:26:

**Comment by MFlisar** [comment]
Sure, I'll do that
