### ISSUE TITLE
How close is Mosby 3 to be production ready?

### ISSUE THREAD

**Issue by mradzinski** [sockeqwe/mosby#219]
Hi everyone!

So, my question is pretty basic: I'm about to begin the development of a new app and I'm trying to decide if to use Mosby 2 or 3. Is Mosby 3 almost there or still not recommended for production usage? I'm gonna be using MVP, so MVI is not needed and out of question.

**Comment by sockeqwe** [comment]
Hi there,
MVI is ready. 
MVP (especially MVP-ViewState) has been refactored a little bit (separate branch MVP here on github). The refactoring mainly completed, but needs some little clean up. Also LCE components will be moved in a separate module. I would say 90% of that is already done and I have plans to finish that over the weekend. My plan is to make a final Mosby `3.0` release on Monday / Tuesday next week. 

I think you should go with latest `3.0-alpha` version or wait until next week for the final 3.0 release ... There might only be a little change of ViewState (Generics) from `3.0-alpha` to the final `3.0`

**Comment by mradzinski** [comment]
@sockeqwe Awesome! I'll go for the 3.0 then. Thanks!
