### ISSUE TITLE
Provide base classes that do not extend from support library

### ISSUE THREAD

**Issue by fmnstr** [sockeqwe/mosby#22]
It would be a nice enhancement to provide alternative classes that do not use support library.

**Comment by IgorGanapolsky** [comment]
Give an example.  You have to extend from AppCompatActivity to get a
Toolbar nowadays....

**Comment by sockeqwe** [comment]
There is already some kind of Delegate you can use to bring the functionality and workflow of MVP and ViewState to other components. I will rename that delegate in Version 1.1 to make it more easier to plugin to your custom base activity, fragment or view class.

See #14
