### ISSUE TITLE
App chrashes

### ISSUE THREAD

**Issue by BayramInanc** [sockeqwe/mosby#221]
Hi, when ı do search  and click one mail suddenly app chrashes.

**Comment by BayramInanc** [comment]
Actually, whenever ı search, let's say, writing 'm' to searchview and then ı pull  down and ı randomly click an mail, then app crashes

**Comment by BayramInanc** [comment]
I did that for maybe 10 15 times, all of them crashed

**Comment by sockeqwe** [comment]
Which app? Which version of Mosby? What's the exception? Could You Please
provide an error stacktrace?

BayramInanc <notifications@github.com> schrieb am Mi., 8. März 2017, 23:25:

**Comment by BayramInanc** [comment]
:) sorry, you are right, ı will do that on saturday, because ı have an important exam. One time, ı failed in that course and don't want again.. :)

**Comment by sockeqwe** [comment]
Good luck... Fingers crossed!

BayramInanc <notifications@github.com> schrieb am Do., 9. März 2017, 08:29:

**Comment by sockeqwe** [comment]
This is fixed now. Thanks for reporting!
