### ISSUE TITLE
custom view cannot be preview

### ISSUE THREAD

**Issue by CLD1994** [sockeqwe/mosby#230]
Hello, my English is very poor...
I need to preview
![image](https://cloud.githubusercontent.com/assets/10044266/24500757/4a77925c-1579-11e7-84a3-c2ff3225b1ed.png)
In my project:
![image](https://cloud.githubusercontent.com/assets/10044266/24500900/f12b9aa8-1579-11e7-89e9-4b1d4c5278ff.png)
thank you！
Mosby Version:3.0.0

**Comment by sockeqwe** [comment]
This is fixed with version 3.0.1

陈蓝度 <notifications@github.com> schrieb am Do., 30. März 2017, 12:53:
