### ISSUE TITLE
Sample Mail - Question

### ISSUE THREAD

**Issue by HowardSchmaeu** [sockeqwe/mosby#254]
you have in your sample mail app a animation/transition on the mails list. If you click in the Menu of Inbox the Mails are shown with an animation from bottom to to. i've try to find the source where you set this but i didn't.
Can you tell me where it is?? :-)

THX in advance

**Comment by sockeqwe** [comment]
Its in MvpLceFragment of the library itself. Take a look at the
showContent() implementation. It calls a class called LceAnimator.

HowardSchmaeu <notifications@github.com> schrieb am Do., 15. Juni 2017,
13:58:

**Comment by HowardSchmaeu** [comment]
ahh okay i got it... thx!!!
