### ISSUE TITLE
com.hannesdorfmann.mosby.mvp.viewstate.lce.data.ParcelableDataLceViewState.readFromParcel

### ISSUE THREAD

**Issue by javajack** [sockeqwe/mosby#27]
[The Most Frequent]
http://crashes.to/s/ac64c0db55d/details

http://crashes.to/s/de64b446301/details

http://crashes.to/s/10ad9ac164c/details

[Recent Crashes]
http://crashes.to/s/144ad441c80/details

**Comment by sockeqwe** [comment]
I have released version `1.1.0` which should fix that bugs. Please update your app and come back if you face any bug!

Thank you very much for your help and for sharing additional information like crash reports!

**Comment by IgorGanapolsky** [comment]
@sockeqwe Thanks for making progress on this.  Have some @changetip $1 bitcoin on me.

**Comment by changetip** [comment]
Hi @sockeqwe, @IgorGanapolsky sent you a Bitcoin tip worth 4,128 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/839323)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
