### ISSUE TITLE
Don't destroy presenter when actvity destroy

### ISSUE THREAD

**Issue by lmdic** [sockeqwe/mosby#291]
In my phone when minimize aplicatoin then the Android destroy activity. In Developer options I turn **"Don't keep activities"**.
Suppose I minimize application. As result the activity is destroy. 
I need to presenter to survive the Activity re-creation. Is it possible on Mosby?

**Comment by sockeqwe** [comment]
No, that's not possible as that is how Android works. Note that's also not possible with any other Framework or Library . Again, you should move things that should live longer than activity / presenter on the outside. 

Also note that " don't keep Activity option" is not simulating real world behavior. Only the whole process is destroyed and not single Activities (as don't keep activity is emulating).
