### ISSUE TITLE
Queuing vs Queueing inconsistency

### ISSUE THREAD

**Issue by jshvarts** [sockeqwe/mosby#293]
I noticed that there is some inconsistency in using words Queuing and Queueing in the project. 
Please let me know if you'd like a PR to update all instances of Queueing to Queuing.

**Instances of "Queuing":**

mvp-queuing-presenter/src/main/java/com/hannesdorfmann/mosby3/mvp/MvpQueuingBasePresenter.java
mvp-queuing-presenter/src/test/java/com/hannesdorfmann/mosby3/mvp/MvpQueueingBasePresenterTest.java
mvp-queuing-presenter/.gitignore
mvp-queuing-presenter/build.gradle
mvp-queuing-presenter/gradle.properties
mvp-queuing-presenter/proguard-rules.pro
mvp-queuing-presenter/src/test/java/com/hannesdorfmann/mosby3/mvp/TestView.java
mvp-queuing-presenter/src/test/java/com/hannesdorfmann/mosby3/mvp/TestPresenter.java

**Instances of "Queueing":**

mvp-queuing-presenter/src/test/java/com/hannesdorfmann/mosby3/mvp/MvpQueueingBasePresenterTest.java

In README:

    // Queueing Presenter for MVP 
    compile 'com.hannesdorfmann.mosby3:mvp-queueing-presenter:3.1.0'
    
    compile 'com.hannesdorfmann.mosby3:mvp-queueing-presenter:3.1.1-SNAPSHOT'

**Comment by sockeqwe** [comment]
oh man, I think `Queuing` should be used. Pull request is very welcome.

**Comment by jshvarts** [comment]
Ok. How do you plan to handle the new artifact name in Gradel dependencies? Upload a duplicate one with a different name starting with this version and keep the old one for older versions?

**Comment by Thomas-Vos** [comment]
I think the README is incorrect. The dependency name is like this: `mvp-queuing-presenter`. (just tested) So there shouldn't be a problem, right?

**Comment by dimsuz** [comment]
Interesting, it looks like both variants are used!
And one is more popular than another: 
https://english.stackexchange.com/questions/60852/queueing-or-queuing

**Comment by Thomas-Vos** [comment]
I think we should use `Queuing`. https://trends.google.com/trends/explore?date=today%205-y&q=queueing,queuing

**Comment by sockeqwe** [comment]
Thanks everybody for your feedback. So turned out it was mostly "just" a README error and the dependency is  already been published under the correct name `mvp-queuing-presenter`: https://search.maven.org/#artifactdetails%7Ccom.hannesdorfmann.mosby3%7Cmvp-queuing-presenter%7C3.1.0%7Cjar

Thanks again, really appreciated it!
