### ISSUE TITLE
How to make a difference between ViewStates with StateReducer?

### ISSUE THREAD

**Issue by larten** [sockeqwe/mosby#294]
Hi,

 In the mvi-sample project you make difference between ViewStates in the render method. It is good, because you change on the view only what changed in the state.
 But how can I solve it, if I'm using state reducer? I lose the information during reduce, but it would be nice to refresh only the changed UI parts.
 
 I checked a few databinding solution and there it's easy to bind a part of view a part of data.

 Sorry if it's not relevant to others, but currently this is my only problem and I try to keep the MVI solution in my apps :D

br,
Larten

**Comment by sockeqwe** [comment]
Hey,
I'm sorry but I don't b understand what you mean. Can you give me a concrete example

**Comment by larten** [comment]
Sure!

Here is a viewstate. The data and list properties are coming from different resources or refreshind in different time.
```java
public class MyViewState {
    private boolean loading;
    private String data;
    private ArrayLis<MyObject> list;
    private Throwable throwable;
}
```
And here is the render method in the view:
```java
@Override
    public void render(MyViewState viewState) {
        if(viewState.isLoading()) {
            // loading handling
        } else if(viewState.getError() != null) {
            // render data and list
        } else {
            // error handling
        }
    }
```
If I trigger an action (press button, anything) and refresh the data property in the viewstate with the reducer, I will also reload the UI parth where I show the list property when I'm rendering.

**Comment by sockeqwe** [comment]
I'm really sorry but I still Don't understand what information you loose?

László Krasnyánszki <notifications@github.com> schrieb am Do., 14. Dez.
2017, 22:54:

**Comment by larten** [comment]
No it's okay, sorry for that and thank you for your time!

Here is an example: (but in the example contains only 3 states of viewstate (loading, data loaded and error)
[https://gist.github.com/larten/10c35f46a11d089e3f321d46aa40e04a](url)

Every time when a state will be changed you will render all views again. Imagine, you have a data class with 20 fields and after some interactions, only one text field changed. Instead of updating one single TextView you will re-render all views.

I think it's unnecessary to update every view. We should update on the UI only what changed (like DiffUtil on RecyclerView).
Maybe I should use subclasses of my EpisodeDetailsViewState for example and when I'm rendering I should make a difference depends on class. But it seems not too elegant solution.
I try to find something like the ObservableField in the MVVM databinding solutions. When you change a property in the viewstate you notify the subscribed UI elements only, if the data changed.

**Comment by sockeqwe** [comment]
that has never been an issue for me and I just can recommend, that until it really gets an issue don't care about it ...

The only one operation that comes immediately into my mind which is expensive is setting text on a `TextView` because this will trigger a whole relayout of the text layout even if the text hasn't changed. 

But again, unless it is really an issue, I wouldn't bother ...
If this, however, becomes an issue someday, I would recommend to determine which UI widgets should be updated in the view layer, maybe manually with `if else` or a librarie like [anvil](https://github.com/zserge/anvil) can help

**Comment by scraplesh** [comment]
@larten I have the same problem as you. As a workaround you can use something like this (_Kotlin_):
```kotlin
viewModel.viewState
    .scan(initialState to true) { (prevState, _), newState ->
        newState to (prevState.toolbarMode != newState.toolbarMode)
    }.filter { (_, changeFlag) -> changeFlag }```

**Comment by scraplesh** [comment]
And here is Kotlin extension function to simplify:
```kotlin
fun <T> Observable<T>.scanFilter(initialValue: T, predicate: (previousState: T, newState: T) -> Boolean): Observable<T> {
  return scan(initialValue to true) { (previousState, _), newState ->
    newState to predicate(previousState, newState)
  }.filter { (_, propertyChanged) -> propertyChanged }
      .map { (viewState, _) -> viewState }
}
```
And a code from my previous comment rewrited with this extension:
```kotlin
viewModel.viewState
    .scanFilter(initialState) { previousState, newState -> previousState.toolbarTitle != newState.toolbarTitle }
```
