### ISSUE TITLE
Status code 500 from jcenter server

### ISSUE THREAD

**Issue by zoltanf** [sockeqwe/mosby#3]
While trying to sync the project for the first time, on 2 machines I get:

> Error:Could not GET 'https://jcenter.bintray.com/com/hannesdorfmann/mosby/core/1.0.0/core-1.0.0.pom'. Received status code 500 from server: Internal Server Error

I have in my build.gradle (plus the apt stuff)
```
compile 'com.hannesdorfmann.mosby:core:1.0.0'
compile 'com.hannesdorfmann.mosby:mvp:1.0.0'
```

Any suggestions?

**Comment by sockeqwe** [comment]
Got this too today, it seems that jcenter has some server issues today ... Alternativley you can use


or 
```groovy

allprojects {
  repositories {
    // jcenter()
     
     mavenCentral()
     
    // or 
     maven {
          url 'https://oss.sonatype.org/content/repositories/releases/'
       }
  }

   // Icepick requires
    maven {url "https://clojars.org/repo/"}
}

```

instead of `jcenter()`

**Comment by zoltanf** [comment]
Thank you.
