### ISSUE TITLE
sample-flow gone

### ISSUE THREAD

**Issue by Empty2k12** [sockeqwe/mosby#309]
Having researched 2018 solutions for the fragment problem I came across your blog post and have been trying to implement the Mosby/Flow combo.

Trying to access the Repo link I noticed that there is no `sample-flow` anymore.

Is using Mosby with Flo not something encouraged anymore, or what is the reason for removal?

Maybe it would be possible to update the blog post explaining why this should/shouldn't be done anymore and what alternatives there are.

**Comment by sockeqwe** [comment]
Given the fact that `flow 1.0` has never been released and is not actively maintained anymore, I think that it flow is not a future proof bet.
I should update the blog post, thanks for the hint.

Maybe [Conductor](https://github.com/bluelinelabs/Conductor) is a alternative and there is a [plugin](https://github.com/sockeqwe/mosby-conductor) for mosby too.
