### ISSUE TITLE
request - update blog post

### ISSUE THREAD

**Issue by fahimk** [sockeqwe/mosby#31]
I know you are currently working on a new blog post for the mail sample. I think since the initial mosby blogpost is the main source of documentation for this issue, it would be nice if that was updated to reflect changes from 1.1.0 (delegates). A better long term solution would be to start using the github wiki.

**Comment by sockeqwe** [comment]
yes, you are right.  I will update my blog post and explain new things introduced in 1.1.0 (incl. delegates) in the upcoming blog post. 

I'm also thinking about setting up a dedicated github site as central resource of documentation (combining the information provided by both blog posts) and javadoc and a if mosby gets more popular.

**Comment by sockeqwe** [comment]
I have update my blog.

Github page is in progress #46
