### ISSUE TITLE
Problem when propagating event

### ISSUE THREAD

**Issue by JStalin98** [sockeqwe/mosby#311]
I have a problem using mosby mvp and the event bus

I am replicating the login example of e-mail and when the login_presenter sends the event "LoginSusscesfullEvent" I get an error that there is no event record and I think it is because in the class of the message pre-sender when the view is passed from this to login to start session, we call the method detachView () that desresgristra the eventbus and and the event is sent before it is called back to atachView to recreate the record, I would not know how to fix it

**Comment by sockeqwe** [comment]
Its not an issue of Mosby. Consider asking this question on stackoverflow.
