### ISSUE TITLE
How can I use it by extents Activity rather than AppCompatActivity?

### ISSUE THREAD

**Issue by Sun-Shuai** [sockeqwe/mosby#313]
How can I user it by extents Activity rather than AppCompatActivity?

**Comment by abyrnes** [comment]
I'm not really sure why you'd want to, but to do so you'd manually have to copy `MviActivity` into your project and just replace the parent class with `Activity`

**Comment by sockeqwe** [comment]
Right, if you take a look at `MviActivity` source code you will see that it basically delegates all lifecycle events to a delegate. You have to do the same for your `Activity` bases class.
