### ISSUE TITLE
MvpBasePresenter and a Retained MvpFragment, reference to view will always be null after rotation

### ISSUE THREAD

**Issue by GNima** [sockeqwe/mosby#32]
Subclassed MvpFragment and in onCreate() setted it to retain instance. after rotating the device isViewAttached() returns false even though attachView() was called.

logs: (when device is rotated)
**without retainInstance:**
>  detachView()
> dropReference()
> attachView(v): view is null? false
> isViewAttached() -> true=true and ?
> getView()```

**with retainInstance**
> detachView()
> dropReference()
> attachView(v): view is null? false
> isViewAttached() -> false=false and ?
>  isViewAttached() -> false=false and ?

log:     Log.d("isViewAttached() -> " +isAttached + "=" + (viewRef != null) + " and ?");
The ? is viewRef.get() != null but it would crash since viewRef is null

**Comment by sockeqwe** [comment]
Hi, thanks for reporting!
I'm not sure If I understand you correctly, but in general: yes the view get attached and detached temporarily during orientation changes even if the fragment is retaining.

I can't reproduce the behaviour described by you. Can you provide a sample? Maybe you forget to calls super methods on overriding methods? Which version of Mosby are you using?

For instance have a look at the `sample-mail`: The `LoginFragment` is retaining instance state and the associated `LoginPresenter`  gets the View attached and detached, but I didn't run in the case where `isViewArrached()` returns false or reference to view in presenter is null.  Can you point me the problem you found on the  code  of the `sample-mail` (if you can not provide your own sample code that has this problem)?

A prerequisite in Mosby is that the Presenter runs on the main UI thread. So ever call from presenter `isViewAttached()` or `getView().setXY()` must run on androids main UI Thread.

**Comment by GNima** [comment]
I couldn't reproduce this, sorry.
