### ISSUE TITLE
Kotlin  - Flow - possibly Multiplatform impl

### ISSUE THREAD

**Issue by micutad** [sockeqwe/mosby#337]
Is something like this planed or do you see some possible problems with this? I just finished watching your Flow presentation from droidcon and it seems like a perfect candidate for replacement of RX in MVI which in ideal world could be used in Kotlin Multiplatform projects.

**Comment by sockeqwe** [comment]
There are mo plans  to do that in the near future but you may find this library useful

https://github.com/freeletics/FlowRedux
