### ISSUE TITLE
How could I have multiple fragments in a Mosby Activity ?

### ISSUE THREAD

**Issue by javajack** [sockeqwe/mosby#34]
I am using Dagger1MvpLceViewStateActivity as you have explained in a MosbyViewPagerDemo app.

I want to create a new fragment that could display "the full story". in the same screen. 
How could that be done ?

**Comment by sockeqwe** [comment]
Having multiple fragments in an Activity is not mosby related. Simply use `getSupportFragmentManager().beginTransaction(). ... .commit()`. However (for simplicity, you may consider start a new activity for "the full story"

**Comment by javajack** [comment]
I did.
App used to crash on a back button press.
What are the best practices for activity navigation ?
Any good article you might want to suggest ?

**Comment by sockeqwe** [comment]
If you want to share your error stacktrace I could try to help you.
Regarding activity navigation, thid are the very basics and should be
covered in any android tutorial... google for android start activity ...

Rakesh Waghela <notifications@github.com> schrieb am So., 17. Mai 2015
15:51:
