### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#35]
- Build and run tests on every commit
- Release SNAPSHOTS to maven central

**Comment by IgorGanapolsky** [comment]
I'm looking forward to this travils.yml file.

**Comment by IgorGanapolsky** [comment]
Do you also need to create an emulator like this?
`before_install:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:22" --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &`

**Comment by sockeqwe** [comment]
no, i was just playing a little bit around with travis and havent found time yet to finalize this script yet ...
