### ISSUE TITLE
Unused methods

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#36]
Hi,
I'm wondering what is the purpose of `onEventMainThread()` methods in this class:
https://github.com/sockeqwe/mosby/blob/master/sample-mail/src/main/java/com/hannesdorfmann/mosby/sample/mail/base/presenter/BaseRxMailPresenter.java#L98

It seems that these methods are unused.  Perhaps they respond to bus events, but I do not see a `@Subscribe` or `onEvent` method annotations?

Thanks,
Igor

**Comment by sockeqwe** [comment]
Hi, 
`onEvent` is the way to register methods on [GreenRobot's EventBus](https://github.com/greenrobot/EventBus).  GreenRobots EventBus doesn't have `@Subscribe` annotations like Otto, instead every method with `onEvent` prefix gets registered on the EventBus. 

`onEventMainThread` is just the way to specify that the EventBus should dispatch the Event on android's main UI thread. GreenRobots EventBus supports dispatching Events through different threads.

You may wonder where the methods gets registered to the EventBus. GreenRobots EventBus supports inheritance quite well. So `BaseRxMailPresenter` doesn't registers itself directly on the EventBus, but its super class [BaseRxAuthPresenter](https://github.com/sockeqwe/mosby/blob/master/sample-mail/src/main/java/com/hannesdorfmann/mosby/sample/mail/base/presenter/BaseRxAuthPresenter.java) does. Hence, all  `onEvent` and `onEventMainThread` methods along the inheritance hierarchy  (inclusive subclasses) gets registered automatically to the EventBus, i.e. [MailsPresenter](https://github.com/sockeqwe/mosby/blob/master/sample-mail/src/main/java/com/hannesdorfmann/mosby/sample/mail/mails/MailsPresenter.java)

Hope that answers your question.

**Comment by IgorGanapolsky** [comment]
Thanks!
