### ISSUE TITLE
Icepick in MvpLceViewStateActivity

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#37]
Hi,
I am trying to use `@Icicle`primitive variable in an activity which extends your `MvpLceViewStateActivity`.  However, it isn't saving the state.  Is this a bug on my end, or MvpLceViewStateActivity?

Thanks,
Igor

**Comment by fahimk** [comment]
Try this: https://github.com/frankiesardo/icepick/issues/50

**Comment by IgorGanapolsky** [comment]
@fahimk So what's the solution?

**Comment by fahimk** [comment]
change from:
```java
compile 'frankiesardo:icepick:3.0.2'
provided 'frankiesardo:icepick-processor:3.0.2'
```
to:
```java 
compile 'frankiesardo:icepick:3.0.2'
apt 'frankiesardo:icepick-processor:3.0.2'
```

**Comment by IgorGanapolsky** [comment]
@fahimk Tried it already.

**Comment by sockeqwe** [comment]
Do you have added the dependency to icepick processor in In your APPS `build.gradle` file?
```groovy
apt 'frankiesardo:icepick-processor:3.0.2'
```

You can debug your code: override onSaveInstanceState and step into super.onSaveInstance() with your debugger until you reach MosbyActivity.onSaveInstanceState().  Do the same in onCreate() to ensure that really icepick is the problem

**Comment by IgorGanapolsky** [comment]
It doesn't matter if I use 'apt' or 'provides'.  Still the same result.
And Icepick works fine elsewhere in my project that isn't extending this
activity.

I guess I'll drill down like you suggested to see the cause...

Igor

**Comment by sockeqwe** [comment]
I cant reproduce your issue. 

I have created a sample test app, where i increment a counter value in `onCreate()`. So with every orientation change the counter value gets incremented. The counter value is saved and restored with `@Icicle`. You can download the sample project from here: https://db.tt/GCzquro9

I think your problem is something else.

**Comment by IgorGanapolsky** [comment]
In your sample, your **createViewState()** method returns  `new ParcelableDataLceViewState<>();` However, in the mosby sample, you are returning ``new CastedArrayListLceViewState<>();`.  Does this have any impact on things, or am I totally looking in the wrong place?

**Comment by sockeqwe** [comment]
The sample should just prove that `@Icicle` works and nothing else. The ViewState is not related to `@Icicile`.

Regarding the ViewState question:
`ParcelableDataLceViewState` is just a ViewState implementation where your model `T extends Parcelable`  while `CastedArrayListLceViewState` is used for a model `ArrayList<T extends Parcelable>`

In other words: If you have a List of Items, then use `CastedArrayListLceViewState`, if you just have a single model class (not a list) then use  `ParcelableDataLceViewState`
