### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#47]
☑ Mosby itself seems to be ready to be used in Kotlin. A little sample project already works as expected.

❑ Third party annotation processors don't work right now, but I haven't tested them with kotlins annotation processing support introduced lately.
   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ❑ **Butterknife**: Probably Butterknife could be replaced with [Kotterknife](https://github.com/JakeWharton/kotterknife), but it's not clear if `Kotterknife` will ever see version `1.0` . However, adding Kotterknife's dependency should be done in the end users app project which uses Mosby and not in Mosby itself. So supporting  Kotterknife is not needed in Mosby itself.
  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ❑ **FragmentArgs**: May need an improved Annotation Processor for Kotlin. However, the goal should be that the dependency to Kotlin's `FragmentArgs` annotation processor should be added in end user application project. See this issue: https://github.com/sockeqwe/fragmentargs/issues/21

 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ❑ **Icepick** doesn't work right now.  See this issue:  https://github.com/frankiesardo/icepick/issues/47

<br /><br />
----------------

`Mosby 2.0` can only be released after all annotation processors work properly and don't conflict with their java counterparts.

**Comment by dalewking** [comment]
In terms of view injection, Kotterknife is not necessarily the best solution. Kotlin has its own support for accessing views of activities and freagments: http://kotlinlang.org/docs/tutorials/android-plugin.html.

I wonder if there would be a way to make the use of these third party libraries more pluggable i Mosby, but I am not sure what that would look like. I am not sure that really should be done at the top of the hierarchy in Mosby. Perhaps they should be moved to a layer under Mosby and leave it to users of Mosby to create their own base layer that adds this support to a base class that extends MvpActivity. You could even provide that layer as an optional layer.

**Comment by sockeqwe** [comment]
Moving the layer would be the simplest solution. However I personally found this as a convenience features in Mosby, even though there might be other developers who doesn't like to use this third party tools. I thought about something like delegation to make it more pluggable, but havent found a good solution yet. I will take it into consideration for Mosby 2.0

**Comment by sockeqwe** [comment]
Kotlin supported in Mosby 2.0
