### ISSUE TITLE
No presenter in MosbyActivity

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#49]
Hello,
why doesn't your MosbyActivity have methods for creating a Presenter?  I do not want to extend any of the complicated LCE activities in the Mosby framework, I just want to stick to MosbyActivity.  What is my option at this point?

Igor

**Comment by sockeqwe** [comment]
Hi,
you are on the right track. `MosbyActivity` is the root `Activity` and just integrates `Butterknife` and `Icepick`. What you are looking for is `MvpActvity` or `MvpFragment` from `mvp` module. It's basically just an Activity / Fragment with `createPresenter()`  method.  If you want to add `ViewState` support then `MvpViewStateActivity` or `MvpViewStateFragment` from `viewstate`module is what you are looking for.

**Comment by IgorGanapolsky** [comment]
Thanks!
