### ISSUE TITLE
RestoreableViewState 

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#50]
Hello,
I have an Activity which `extends MvpLceViewStateActivity`.  However, when I try to launch it, I get this Exception:
<b> java.lang.IllegalArgumentException: Only RestoreableViewState are allowed</b>

Please advise,
Igor

**Comment by IgorGanapolsky** [comment]
I see what the problem is:
in createViewState() method, I have to `        return new CastedArrayListLceViewState<>();
`

**Comment by sockeqwe** [comment]
exactly
