### ISSUE TITLE
pullToRefresh is always false

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#51]
Hello,
My Activity is extending `MvpLceViewStateActivity`.  However, `loadData(boolean pullToRefresh)` method will always have pullToRefresh <b>false</b>.  Please explain how I can make it true?

Thanks,
Igor

**Comment by sockeqwe** [comment]
Hi,
the idea is that this methud gets called from your pull to refresh mechanism as well like `SwipeRefreshLayout` and that one passes true as parameter. Have a look at the simple example (sample folder)

**Comment by IgorGanapolsky** [comment]
It does not have to be triggered by PullToRefresh action.  This method is
triggered when loading data when activity comes on the screen.

**Comment by sockeqwe** [comment]
yes, if activity comes on screen then loadData(false) gets triggered. If
you want to implement pull-to-refresh by using `SwipeRefreshLayout` then
you should trigger manually from your `OnRefreshListener` loadData(true).

Igor Ganapolsky <notifications@github.com> schrieb am Di., 9. Juni 2015
17:22:
