### ISSUE TITLE
Annotated adapter exception

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#52]
Hello,
I keep getting an exception from the AnnotatedAdapter in the ViewHolder:
> android.content.res.Resources$NotFoundException: String resource ID #0x1

This doesn't make sense because other views in the ViewHolder can be set just fine.  It is this one view that is causing the problem.

Please advise,
Igor

**Comment by IgorGanapolsky** [comment]
I figured out the problem.  Apparently you cannot set TextView text with an Integer.  You have to convert it to a String first!  Very misleading error...

**Comment by sockeqwe** [comment]
Oh yeah, struggled upon that several times too :smiley:
