### ISSUE TITLE
LINT check for isViewAttached()

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#53]
Write a custom LINT check that throws a warning if `presenter.getView()` is used without checking `presenter.isViewAttached()`

**Comment by sockeqwe** [comment]
Related to #55

**Comment by Tiny-Times** [comment]
@Override
    public void detachView(boolean retainInstance) {
        if (view != null) {

            Type[] types =
                    ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments();

            Class<V> viewClass = (Class<V>) types[0];
            view = NoOp.of(viewClass);
        }
    }

I found view always null.

**Comment by sockeqwe** [comment]
are you sure that you have ever attached a view to the presenter? How does you presenter implementation looks like?

**Comment by snowpong** [comment]
What is the point of `isViewAttached()` really, why not use `getView() != null`? It does the same and no need for extra LINT rule :)

**Comment by sockeqwe** [comment]
Good point!

**Comment by RoRoche** [comment]
What about adding a method as follows:

```java
@NonNull
public V getViewOrThrow() {
    final V view = getView();
    if (view == null) {
        throw new IllegaStateException("view not attached");
    }
    return view;
}
```

**Comment by sockeqwe** [comment]
This should be another presenter class imho  and not part of `MvpBasePresenter`.

**Comment by sockeqwe** [comment]
@RoRoche I just realized that `getViewOrThrow()` is basically the same as:

```java
getView().doSomething();
```
because without any `if (getView() != null) ` or `if (isViewAttached())` check it will crash with a `NullPointerException`. So this seems to be an implementation detail on developers site.

**Comment by RoRoche** [comment]
It was mainly about the `@Nullable` annotation on `getView` that causes a LINT warning on `getView().doSomething();`. But I just realized that `getView` is not nullable anymore in mosby3, so all is fine for me now ;)

**Comment by sockeqwe** [comment]
`getView()` is deprecated in `3.1.0`. See #274. Issue fixed 😄
