### ISSUE TITLE
annotated with @ViewType.

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#54]
Hello,
I am getting the following compilation error:

> Error:(30, 37) error: mHousecalls in HistoryListAdapter is not public. Only final integer fields with public visibility can be annotated with @ViewType.

This does not make sense to me.  Please elaborate...

Igor

**Comment by sockeqwe** [comment]
Hi, as the error message indicates you have to annotate integer fields that are public and final.

```java
@ViewType(...)
public final int myViewType = 0;
``` 

Btw. please report issues on  [AnnotatedAdapter](https://github.com/sockeqwe/AnnotatedAdapter) repo, not on Mosby because AnnotatedAdapter is not related to Mosby.

**Comment by IgorGanapolsky** [comment]
But mHousecalls is a List, not an integer!!

**Comment by sockeqwe** [comment]
Ok, let's continue the discussion at https://github.com/sockeqwe/AnnotatedAdapter/issues/13
