### ISSUE TITLE
Metadata annotations

### ISSUE THREAD

**Issue by jenzz** [sockeqwe/mosby#55]
Hi @sockeqwe!

Have you considered annotating all public methods and its non-primitive parameters with the new [support annotations](http://tools.android.com/tech-docs/support-annotations)?
I find them incredibly useful since Android Studio gives you some nice little hints in the IDE, e.g. `getView()` in `MvpBasePresenter` is [@Nullable](https://developer.android.com/reference/android/support/annotation/Nullable.html).

Cheers
jenzz

**Comment by sockeqwe** [comment]
Hi, it's definitely on my TODO list! I have plans to do that in the next 2 weeks ...
