### ISSUE TITLE
MosbyFragment vs MvpLceFragment

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#57]
Hello,
I am trying to decide on the best use-case between these types of fragments.  I have a fragment in my app that will fetch data from the DB and present it in a RecyclerView.  There won't be a visible loading state like in your LCE spinner examples (since DB queries are lightning fast).  So, can you please tell me which type of fragment is better for my use-case?

Thanks,
Igor

**Comment by lurbas** [comment]
Com'on, you are so annoying. Stop spamming issue tracker! MosbyFragment is only a base. You're not suppose to extend it directly. Use MvpFragment or MvpViewStateFragment. I hope it's your last silly issue. Learn how to read with understanding, or develop some problem-solving skills...

**Comment by sockeqwe** [comment]
Indeed, the issue tracking is not really meant for such questions.
However, I have to say that currently there is no place for all resources. I have plans to setup a github page for Mosby to collect all resources in one place (incl. javadoc) #46 , but I haven't found time yet to do so and I'm dreaming of getting such questions asked and answered on stackoverflow.

Regarding your question: @lurbas  is right:
- `MosbyFragment` is just the base class for all fragments which already sets up butterknife, fragmentargs and Icepick. 
- `MvpFragment` extends `MosbyFragment` and adds `Presenter` and `createPresenter()` into the lifecycle of the Fragment
- `MvpLceFragment` extends `MvpFragment` is basically just a template Fragment for displaying different LCE Views (Loading - Content - Error). If you don't have "Loading" then don't use this one.

So `MvpFragment` is what you should use.

Btw. the same classes with the same naming convention are available for Activities, ViewState and Dagger1 as well

**Comment by IgorGanapolsky** [comment]
@sockeqwe Currently, your <b>AboutFragment</b> extends MosbyFragment: https://github.com/sockeqwe/mosby/blob/master/sample-mail/src/main/java/com/hannesdorfmann/mosby/sample/mail/profile/about/AboutFragment.java#L19.

If what you said above is true, then why provide a sample which extends something which isn't meant to be extended directly?

**Comment by IgorGanapolsky** [comment]
@sockeqwe If you don't want people asking you questions about your samples on Github, then why be an open-source developer?

**Comment by sockeqwe** [comment]
`AboutFragment` displays static content ... therefore it doesn't need a presenter, hence it uses `MosbyFragment` and not `MvpFragment`

I'm not saying that I don't want to answer question, I only think that the issue tracker is like the name suggests for reporting issues ...

**Comment by IgorGanapolsky** [comment]
@sockeqwe How would one know that static content should be loaded with MosbyFragment.  Is it explicitly written somewhere?  
> study the code by your own
Umm, it isn't college.  It is github - which encourages collaboration. You should be thankful that people are looking at your samples and coming up with questions, instead of supporting rude and offensive users above.

**Comment by sockeqwe** [comment]
You are very welcome to contribute to this project and also to ask questions. Until now I tried my best to answer your questions even beyond Mosby related things, like ViewHolder in RecyclerView and some Dagger basics.

However, I can also expect that before asking you have tried to solve the problem you are facing by your own, i.e.by browsing the source code and understand the source code and so on.

If you have a closer look at AboutFragment you will see that there is a variable Person and all this fragment does is display the persons data. I think that this can be seen very easily by just reading over those 30 lines of code of AboutFragment.
Next you may wonder why I use MosbyFragment and not MvpFragment.

If you jump into the source codes of this classes you see in the java doc stating what the classes are for:
https://github.com/sockeqwe/mosby/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/MvpFragment.java
https://github.com/sockeqwe/mosby/blob/master/core/src/main/java/com/hannesdorfmann/mosby/MosbyFragment.java

And even if there would be not enough information provided by javadoc I guess reading the source code which are just 50 lines of code each should make things more clear.

And yes, there is nowhere specified that static content should be displayed by just using MosbyFragment (even though I pointed that in Tipp 11 on  http://hannesdorfmann.com/android/mosby-playbook/  ) , but you can't expect that every scenario you are facing is documented somehow. At this point I can expect that someone think of oneself.

However, I agree Mosby needs a little bit more documentation and a central point for all resources. I will setup a github page, but I haven't found time yet ( I'm have a regular full time job ). Probably there will be a section for questions or a way to write comments, where you could ask such questions. Ideally such things would be asked and answered on stackoverflow ...
I just say that issue tracker is not the right place for such questions, but I also have to admit that there is currently no other place for such questions.

All I want is that before asking try to understand the code, search javadoc, google for it

**Comment by IgorGanapolsky** [comment]
I was gonna leave this issue alone, but you and @lurbas have been condescending and tempted further arguments here.

> all this fragment does is display the persons data
I can say the same about <b>MailsFragment</b>: all this fragment does is display the mails data.  Yet MailsFragment extends <b>BaseMailsFragment</b>, which in turn extends <b>BaseMailView</b>.  How is that intuitive??

> even though I pointed that in Tipp 11 on http://hannesdorfmann.com/android/mosby-playbook/
Well, this isn't college, and yours isn't a textbook.  So you can expect some people may miss your playbook information.

> such things would be asked and answered on stackoverflow
Mosby isn't ubiquitous on StackOverflow, and therefore users are compelled to ask these questions on your Github repo page.

I never expected to be treated so irreverently on Github, especially after contributing pull requests and donating some bitcoin to a project.

**Comment by sockeqwe** [comment]
I apologize it wasn't my intention.

See the difference is that `MailsFragment` loads a list of Mails in background thread. Therefore it implements MVP pattern. The `AboutFragment` displays a `Person` which has been passed as Intent extra data (so it doesn't load data in an async thread) and therefore  `AboutFragment` **does not** implement MVP (hence it uses `MosbyFragment` and not `MvpFragment`).


If the Mail example is to complex, then you should check out the other sample apps where more basic stuff of how to use Mosby is implemented.


I said: 
>  I'm dreaming of getting such questions asked and answered on stackoverflow

I will try to create a place for such questions as part of Mosby's github page. Until done you can ask questions here. All I expect is that you have investigated the code by yourself more then 5 minutes, think of one self and play around a little bit with the sample code before asking. If it's really still unclear, then go ahead and ask your question here.

Once again, I apologize, I didn't wanted to be rude.
From my point of view everything is fine and we can put a end to this discussion.

**Comment by IgorGanapolsky** [comment]
> hence it uses MosbyFragment and not MvpFragment

If someone would've explained it this way in the beginning (instead of being disrespectful @lurbas), this long disturbing conversation thread would've have been avoided.

**Comment by lurbas** [comment]
I understand people can have questions not directly connected with an actual issue, but the thing is there were like 5 or 6 of them in past couple of days. If someone (@sockeqwe) took lots of his free time and develop this framework, all others could spend some time and really try to understand it or solve their problem by them own. Being an "open source developer" doesn't mean you have to babysit everyone.
The second thing is people are watching this repository because the want to be notified about issues/bugs/potential crashes that other contributors have found. It's a waste of my time to came here every time I receive notification and found out that you have a personal dilemma.
Maybe I wrote my prev message in a little disrespectful form, so my apologies. I hope we can end this discussion now.
