### ISSUE TITLE
Migrate to Butterknife 7

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#59]

**Comment by IgorGanapolsky** [comment]
Please do this.  I cannot use Butterknife 7 in MvpLceFragment because of this....

**Comment by sockeqwe** [comment]
In the meantime you could use Delegate to set up your own base fragment:
explained http://hannesdorfmann.com/android/mosby-playbook/  (Tip 22)

I think migration will be don not before mid July (I also have to do some
other things)

Igor Ganapolsky <notifications@github.com> schrieb am Mi., 1. Juli 2015 um
07:36 Uhr:

**Comment by cody1024d** [comment]
Any update on this?  I'm having the same issue, and it's prohibiting me from using Mosby on a personal project.  Can I fork it and then submit a PR?

**Comment by sockeqwe** [comment]
Hi, a few hours ago I have released version `1.1.1` containing some minor bug fixes / code clean up. As this is out now, we can continue to working on `1.2` which basically is "Migrate to Butteeknife 7". Hence Pull Requests are very welcome, otherwise I will try to find time for that next weekend

**Comment by cody1024d** [comment]
No worries.  I created a Pull Request that *should* contain all the changes necessary to support ButterKnife v 7.0.1

**Comment by sockeqwe** [comment]
Thanks for the pull request.

There are some other (minor) things I want to address with version `1.2.0` for which I hopefully find time next weekend. In the meantime you can use `1.2.0-SNAPSHOT`, which contains Butterknife 7 support.

```groovy
allprojects {
  ... 
  // Sonatype SNAPSHOT repository
repositories {
    maven{
      url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }

   ...
}
```

However, I'm considering to remove Butterknife, FragmentArgs and Icepick  in `Mosby 2.0` to avoid such problems (that I have to migrate manually). By removing them I also can fully support Kotlin faster (see #47 )

**Comment by IgorGanapolsky** [comment]
Why is Icepick  problem?

**Comment by sockeqwe** [comment]
The same problem as with Butterknife could be occur. What if icepick's API change in 3 months. Then we also have to migrate Mosby to make it work and it also may breaks backward compatibility i.e: Now Butterknife 7 is required in Mosby `1.2.0`  you can not use Mosby 1.2.0 as long as you haven't migrate your app to Butterknife 7. 

Regarding Kotlin:  I'm not 100% sure, but I think that Kotlin has some other accessibility behaviour as java. As far as I know there must be a setter method used for each field which doesn't has to declared in your Kotlin class but will kind of "generated" internally by Kotlin. And you have to set the value  of a field by using the corresponding setter method. The Annotation processor must be changed to use the setter instead of accessing the field directly like it's done at the moment in java.

**Comment by IgorGanapolsky** [comment]
So we would be getting rid of Icepick's orientation handling
functionality...

**Comment by sockeqwe** [comment]
See #63
