### ISSUE TITLE
Remove Butterknife, FragmentArgs and Icepick

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#63]
We had the problem with migrating from `Butterknife 6` to `Butterknife 7`. What if other libraries  API like Icepick change in 3 months? Then we also have to migrate Mosby to make it work and it also may breaks backward compatibility i.e: Now `Butterknife 7` is required in `Mosby 1.2.0` . You can not use `Mosby 1.2.0` as long as you haven't migrate your whole app to `Butterknife 7`. You can not use `Mosby 1.2.0` with `Butterknife 6`.

We will just remove `MosbyFragment` and `MosbyActivity` which is currently the supper class in your inheritance hierarchy. A concrete example how your inheritance hierarchy  currently look like:
- **MosbyFragment (uses Butternknife, FragmentArgs and Icepick)**
   - MvpViewStateFragment (extends MosbyFragment) 
       - MyAppsFragment (extends  MvpViewStateFragment) 

So all your Fragments are depending on **MosbyFragment**  and in other words are depending on the currently used version of Butterknife, FragmentArgs and Icepick as defined internally in `Mosby`

In the future inheritance hierarchy in your app should look like this:
 - MvpViewStateFragment
    - **MyAppsFragment (extends MvpViewStateFragment, uses Butternknife, FragmentArgs and Icepick**

An advantage is that the developer using Mosby can now freely choose what additional libraries he want to choose (i.e. he can left out Icepick completely). However the disadvantage is that the developer using Mosby has to insert Butterknife, FragmentArgs and Icepick by hand. This could be reduced by adding an extra class like this:

- MvpViewStateFragment
   - **MyAppsBaseFragment (extends MvpViewStateFragment, uses Butternknife, FragmentArgs and Icepick**
       - MyAppsFragment (extends MyAppBaseFragment). 

That will reduce the amount kick in Butterknife, FragmentArgs and Icepick things, but it still has to be done once per app (since `MyAppBaseFragment` is not part of mosby libraray)

Also it allows us to fully support kotlin faster ( see #47 ) since we don't have to wait until Butterknife (doesn't make sense in Kotlin at all), Icepick and FragmentArgs support Kotlin as well.

**Comment by cody1024d** [comment]
I think this is 100% the right direction, and decouples the use of this as an MVP library, instead of it being a framework with multiple dependencies

**Comment by sockeqwe** [comment]
Jep, I also think that developers can move their `MyAppsBaseFragment` (uses Butternknife, FragmentArgs and Icepick) in a own library if they don't want to write a `BaseFragment` again and again. This allows them also to use a older version of `Butterknife` or whatever with the latest version of  `Mosby`.

**Comment by sockeqwe** [comment]
Also removed Retrofit, Dagger and RxJava dependencies for same reason

**Comment by twig** [comment]
Thank you for this.

I didn't want to install IcePick because I already had Parcelable.

**Comment by IgorGanapolsky** [comment]
@twig Does Parcelable cancel out Icepick?

**Comment by twig** [comment]
@IgorGanapolsky No not at all, but they're similar enough that I didn't want to duplicate libraries.
