### ISSUE TITLE
getLastNonConfigurationInstance() for retaining Activity Presenters

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/mosby#64]
We could use `onRetainNonConfigurationInstance()` and  `getLastNonConfigurationInstance()` to make presenter for activities survive orientation changes.

Unfortunately, `getLastNonConfigurationInstance()` has been marked as `@Deprecated`. Imho this has been done overhasty because retaining fragments and loaders use LastNonConfigurationInstance internally. 

On the other hand we shouldn't relay on `@Deprecated` API. 

Probably this "workaround" could also be used to create retaining presenters for `android.view.ViewGroup` ...

**Comment by brianguertin** [comment]
@sockeqwe Fortunately, you can use [onRetainCustomNonConfigurationInstance](http://developer.android.com/reference/android/support/v4/app/FragmentActivity.html#onRetainCustomNonConfigurationInstance%28%29) which is *not* deprecated

**Comment by IgorGanapolsky** [comment]
@Brian. That's a mouthful of a name :)

**Comment by sockeqwe** [comment]
Yes, that should work.  However, `onRetainCustomNonConfigurationInstance()` is a method defined in `FragmentActivity`. Therefore this method does not exists in plain old [Activity](https://developer.android.com/reference/android/app/Activity.html). I wanted a solution that works universally for both. But I'm not sure if that will work since `onRetainNonConfigurationInstance()` is marked as `final` in `FragmentActivity`. Hence, this method cannot be overridden anyway.

I guess `onRetainCustomNonConfigurationInstance()` can be used and the plain old Activity (not FragmentActivity) has to override `onRetainNonConfigurationInstance()`.

Thanks for the tip @brianguertin !

**Comment by sockeqwe** [comment]
Implemented, will be part of Mosby 2.0

**Comment by guelo** [comment]
I know this issue is closed but @commonsware discovered and @adamwp confirmed that onRetainNonConfigurationInstance is being undeprecated in N: https://twitter.com/adamwp/status/720612665136009218

**Comment by farmazon3000** [comment]
> Implemented, will be part of Mosby 2.0

Is it? When I search for "getLastNonConfigurationInstance" in Mosby I get 0 results.

>  However, onRetainCustomNonConfigurationInstance() is a method defined in FragmentActivity. Therefore this method does not exists in plain old Activity.

So why not use FragmentActivity instead of Activity just for that reason?

**Comment by sockeqwe** [comment]
It is implemented. You can have Activities with presenter that survive screen orientation changes since Mosby 2.0. simply extend from MvpActivity or  MvpViewStateActivity (or LCE variants) and call setRetainInstance(true) in onCreate()

**Comment by farmazon3000** [comment]
Ah OK, it is implemented but not like the title suggested with `onRetainNonConfigurationInstance` but with `setRetainInstance`.

**Comment by sockeqwe** [comment]
Under the hood Mosby 2.0 uses `onRetainNonConfigurationInstance()`

**Comment by farmazon3000** [comment]
Is possible to see the code then, as I said

> When I search for "getLastNonConfigurationInstance" in Mosby I get 0 results.

**Comment by guelo** [comment]
It actually uses getLastCustomNonConfigurationInstance/onRetainCustomNonConfigurationInstance.

**Comment by dimsuz** [comment]
@farmazon3000 you should search for `onRetainCustomNonConfigurationInstance` instead
