### ISSUE TITLE
Cannot use Butterknife 7

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#66]
Hi,
Since I upgraded to Mosby 1.1.1 , I cannot launch my app at all.  It crashes with:
> NoSuchMethodError: No static method inject(Landroid/app/Activity;)V in class Lbutterknife/ButterKnife; or its super classes (declaration of 'butterknife.ButterKnife' appears in /data/app/com.chaione.healthhousecalls.drnow-1/base.apk)

**Comment by sockeqwe** [comment]
Are you sure you are using `1.1.1`  and not `1.2.0-SNAPSHOT` ?

**Comment by IgorGanapolsky** [comment]
Absolutely sure.

**Comment by sockeqwe** [comment]
It seems that you are using  Butterknife 7 with Mosby `1.1.1` because butterknife 7 has renamed `Butterknife.inject()` to `Butterknife.bind()`

Butterknife 7 is supported with `1.2.0-SNAPSHOT`

**Comment by IgorGanapolsky** [comment]
Oh darn.  That makes sense!  Thx

**Comment by sockeqwe** [comment]
you are wlecome!

**Comment by IgorGanapolsky** [comment]
@sockeqwe Thanks for making progress on this.  @changetip $1

**Comment by changetip** [comment]
Hi @sockeqwe, @IgorGanapolsky sent you a Bitcoin tip worth 3,399 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/870714)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
