### ISSUE TITLE
MvpLceActivity and MvpLceFragment contentView animation bug on Lollipop 5.1

### ISSUE THREAD

**Issue by sargunster** [sockeqwe/mosby#69]
When loading the contentView in a layout which contains an AppBarLayout on Lollipop 5.1 (API 22), the content animates in below the tabs (as if they weren't there) and then snaps into the proper place once the animation finishes. It's a little hard to explain, [so here's an apk to showcase the problem](http://weew.ee/psS5G).

Use the drawer to navigate to the Dining Courts section and you'll see it happen. It works fine on API 16 to 21. The bug only occurs on API 22 as far as I know.

**Comment by sockeqwe** [comment]
I can't open the file (seems to be corrupt) but I guess I know what you are talking about. I don't think that this a bug of Mosby. To me it seems that it's more a bug of design library or at least a misbehaviour while doing translationY animations.  It seems that `AppBarLayout` or `CoordintorLayout` makes internally use of `transaltionY` property. 

You should may consider to report this bug on googles bug tracker as well:
https://code.google.com/p/android/issues/list

The easiest workaround is to override the animation in `MvpLceActivity` and `MvpLceFragment`. You can override `protected void animateContentViewIn()`. I guess doing a simple cross fade animation will do the job. 

Let me know if that helps.

**Comment by sargunster** [comment]
I'm not familiar with how animations work in Android, but I'll try it out and let you know how it goes. I don't know much about the underlying issue in the design library, so I don't think a report from me would have enough information to be useful. Perhaps you or someone else could report it on Google's bug tracker?

**Comment by sockeqwe** [comment]
I will do that if you can provide me your XML layout and maybe your apk file ...

Regarding animation: You could copy and paste the related animation code from `showContent()` method. Just remove everything that contains `translationY` :)

https://github.com/sockeqwe/mosby/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/lce/LceAnimator.java

**Comment by sargunster** [comment]
Here's the APK, hosted on Dropbox this time: https://dl.dropboxusercontent.com/u/15518568/app-release.apk

Layout files are in my repo here: https://github.com/sargunster/purdue-dining-courts-android/tree/v2-rewrite/app/src/main/res/layout

The relevant layouts are `activity_main` and `fragment_location_list`. The are used by an MvpLceActivity and a MvpLceFragment, respectively. 

Apologies for my code being a mess :)

I'll try the workaround for the animation later today, once I fix some other, probably unrelated, problem in my app.

**Comment by sargunster** [comment]
The workaround worked, thanks!
