### ISSUE TITLE
java.lang.ClassCastException on MvpNullObjectBasePresenter

### ISSUE THREAD

**Issue by polbins** [sockeqwe/mosby#77]
We have an app with proguard enabled and we had problems with the casting of the MvpView, on MvpNullObjectBasePresenter:

      Class<V> viewClass = (Class<V>) view.getClass().getGenericInterfaces()[0];
      view = NoOp.of(viewClass);

The class that implements MvpView, also implements "SwipeRefreshLayout.OnRefreshListener", which resulted to the ClassCastException (seems that the first generic interface that it got was the OnRefreshListener and not the MvpView, I'm not sure though).

I've added a quick fix which attempts to cast of all the interfaces:

            Type[] types = view.getClass().getGenericInterfaces();
            for (int i = 0; i < types.length; i++) {
                Type type = types[i];
                try {
                    Class<V> viewClass = (Class<V>) type;
                    view = NoOp.of(viewClass);
                    return;
                } catch (ClassCastException cce) {
                    continue; // move on to the next interface
                }
            }

Please check if the fix is okay. TIA! :)

**Comment by sockeqwe** [comment]
I see, thanks for reporting.

Thanks for the workaround. This should work. I will think about another solution this weekend, but by now I don't can think of any better solution than that.

**Comment by sockeqwe** [comment]
Fixed in version `1.3`. I access the generic type of  Presenter to retrieve the view class
