### ISSUE TITLE
MosbyFragment extends support.v4.Fragment?

### ISSUE THREAD

**Issue by TheRishka** [sockeqwe/mosby#79]
But I don't want to support api < 11. Is there any option to use normal fragmentManager and keep using Mosby library? It's kinda hard to implement material animation on support fragments=/

**Comment by sockeqwe** [comment]
Api < 11 means before Honeycomb (Android 3.0). So you want to support Android 2.x? 

I think you are talking about using `android.app.Fragment` (not from support library), don't you?

If so, yes it's possible to bring Mosby's internal functionality to every kind of Fragment by using delegation, see mosby's github page:
 - http://hannesdorfmann.com/mosby/mvp/ (somewhere in the middle, "Delegation" is the headline)
 - http://hannesdorfmann.com/mosby/viewstate/  (scroll down to the end)
 - The statistics Dialog from the mail sample shows how to do that: https://github.com/sockeqwe/mosby/blob/master/sample-mail/src/main/java/com/hannesdorfmann/mosby/sample/mail/statistics/StatisticsDialog.java

But that only brings MVP and ViewState management to your custom Fragment. You still have to kick in Butterknife, FragmentArgs etc. as needed manually

**Comment by gim-** [comment]
Doesn't that mean that if someone wants MvpLceViewStateFragment as `android.app.Fragment` they have to implement everything from MvpLceViewStateFragment to keep the functionality it provides? Is it really necessary to use v4 support library for legacy API versions and not to provide a better option to use `android.app.Fragment` as a base class for their application with Mosby MVP in 2017?

**Comment by sockeqwe** [comment]
yes, that means that you have to copy & paste it, but it should be very easy. Basically all you have to change are the imports from `support.v4.Fragment` to  `android.app.Fragment` 

> use android.app.Fragment as a base class in their application with Mosby MVP in 2017

It is very very unlikely that you will ever use `android.app.Fragment` in your app (or at least you shouldn't), even if you target only the latest Android sdk release, let's say `minSDK = 26`. Support library Fragments have a lot, I repeat it A LOT, more bugfixes and work much more stable and reliable then the platform specific `android.app.Fragment`. Support Fragments get regularly updates and bugfixes which obviously can't be done for `android.app.Fragment`. Also, SupportFragments include additional advantages and backwards compatibilities like `MediaRouter` Support etc.

I definitely can't see that an App should be build without the support library, same for support Fragments. Support library will never disappear imho, so do support Fragments.

**Comment by gim-** [comment]
@sockeqwe Thank you for the info, I'll keep that in mind :)

**Comment by sockeqwe** [comment]
Just for clarification, you only have to copy and paste the
MvpViewStateFragment class and the corresponding Delegate, not the rest of
the Mosby

Andrejs Mivreņiks <notifications@github.com> schrieb am Mo., 27. März 2017,
18:35:
