### ISSUE TITLE
Sample-Mail App

### ISSUE THREAD

**Issue by oderayi** [sockeqwe/mosby#82]
Hello, 

It would be great to see the sample-mail app as a top level project using just the mosby library as a dependency. That way it would be easier to see how mosby can be integrated into an existing app.

In the meantime, could you guide me on how to isolate the sample-mail app and make it a top level project in Android Studio without having to compile all the dependencies?

Thank you for this great library.

**Comment by sockeqwe** [comment]
No, that makes refactoring to painful because if I refactor i.e. rename something in Mosby's internal library I might have to rename it in the mail sample project manually.

Importing in Android Studio is easy: Simply import the root gradle.build file, then yes you have the other modules visible in Android Studio, but simply start (green play button) sample mail.

**Comment by IgorGanapolsky** [comment]
@oderayi. What do you mean "isolate"?  Android Studio (as Intellij) has
been working with modules for years.  This is not something new.  Just run
the sample mail app as an Android module, while adding the needed
dependencies in its build.gradle file if you wish.

**Comment by oderayi** [comment]
@IgorGanapolsky Maybe I asked the question in a wrong way because I am relatively new to Android/Java. 

My question is: Can I use Mosby without seeing its source or having its source loaded into my project?

Thanks

**Comment by IgorGanapolsky** [comment]
@oderayi You can use Mosby in yout app simply by including the relevant
(what you need) mosby dependencies in your app module's build.gradle file.
You do not need to inspect the source code of Mosby.  However, if you wish
to become proficient in using Mosby, it would behoove you to study things
like MvpLceFragment and MvpLceActivity.

**Comment by sockeqwe** [comment]
The only thing you have to do in your project is to replace `compile project (':viewstate)` with `compile com.hannesdorfmann.mosby:viewstate:2.0.0` in the dependencies section. This is not mosby related, its gradle androids build system that allows you to integrate libraries in your project.

**Comment by oderayi** [comment]
@sockeqwe  Yeap, that's what I was hoping someone would mention. 

I guess I have to figure out myself how to decouple the sample mail app from the mosby project, and use the necessary dependencies.

Thank you!
