### ISSUE TITLE
sample-dagger2-rx: fix Dagger 2 scopes

### ISSUE THREAD

**Issue by ersin-ertan** [sockeqwe/mosby#91]
I've incorporated the dagger 2 scopes with subcomponents for the project(as a practice exercise, which could lead up to fixing the mail sample in issue https://github.com/sockeqwe/mosby/issues/39), if you want to [check it out](https://github.com/ersin-ertan/android-ui/tree/master/mosby/src/main/java/com/nullcognition/mosby). I could also create a pull request if you wanted that sample updated.

If you do check it out, what do you think of the design/components and scoping.

**Comment by sockeqwe** [comment]
Thanks, i will check it out next week, but I'm not an dagger 2 expert :smile:

**Comment by IgorGanapolsky** [comment]
@ersin-ertan What is your `ReposComponent

**Comment by ersin-ertan** [comment]
I appears to be ```ActivityComponent```
https://github.com/ersin-ertan/android-ui/blob/1407a6b9cf27d7016912d6b3891518ec830854b6/mosby/src/main/java/com/nullcognition/mosby/di/activity/ActivityComponent.java
