### ISSUE TITLE
Add a tl:dr; documentation

### ISSUE THREAD

**Issue by legarspol** [sockeqwe/mosby#92]
Hi !

We finally migrated to Mosby 2.0. Having a lightweight documentation would have been and still might be really usefull. I would love to get a simple list of name of Mosby's fragment, activity, presenter, and viewstate which come out of the box. For now we have to read all the 3 pages, 1 miles long of documentation to gather a few name or wander among the package of the source code.

It's an idea of enhancement I think would help people to better apprehend the library.

**Comment by sockeqwe** [comment]
Hi,
have you already seen the [github page](http://hannesdorfmann.com/mosby/) ? Or in other words do you think that github page is to long to read? There is a javadoc link where you should see all classes, like viewstates, fragments etc. Also there is a little decision hepler chart that shows which Activity, Fragments are available and when to use them.

**Comment by legarspol** [comment]
Ho ! Where is the decision chart ? This is what I need.

**Comment by sockeqwe** [comment]
See FAQ on githubpages

legarspol <notifications@github.com> schrieb am Fr., 9. Okt. 2015 18:32:
