### ISSUE TITLE
SampleMail: a small issue with the Refresh...

### ISSUE THREAD

**Issue by HowardSchmaeu** [sockeqwe/mosby#96]
If i go crazy with the Swipe Refresh thing and do it really fast again and again... then this tiny refresh symbol just stuck on the screen. I don't have this issue on Mosby 1.2 but on the newest version. i also get this only on real devices (Nexus 5) not on Genymotion ... 

![bild 055](https://cloud.githubusercontent.com/assets/11573181/10755723/b5c8dff8-7c9f-11e5-84d2-b8ffb66f1cce.jpg)

**Comment by sockeqwe** [comment]
I think that is a `SwipeRefreshLayout` issue (support library). Please report this issue in support library issue tracker.
