### ISSUE TITLE
Suggestion: MVPActivity and alike should not implement MVPView

### ISSUE THREAD

**Issue by joseprl89** [sockeqwe/mosby#97]
First of all, congrats on an awesome library.

The only issue I can find is that MVPActivity and similar classes implement by default MVPView. In my opinion, this encourages using the Activity as a view, instead of extracting this responsibility into a different class, and keep the activity managing the Android lifecycle.

I'd suggest removing the realisation of MVPView in those classes, and adding a createView method, mirroring the already existing createPresenter one.

Thoughts around this?

Cheers

**Comment by sockeqwe** [comment]
Hi, I do understand your concerns. I, personally, don't have an additional View class. Actually, I do treat the Activities as views (in a very high level point of view on MVP, see http://hannesdorfmann.com/mosby/images/mvp-controller.png , I treat Activity as view by let it implement the View interface). 

So yes, the current implementation encourages you to use Activity as view. Nevertheless you can still provide your own view class implementing `MvpView` and pass that one to the presenter. You can do this by overriding `getMvpView()` in `MvpActivity` 

But yes, this is not obvious and you are right it still encourage you to see Activity as View which from my point of view is a personal preference or not if you want an additional view object or not.

However, you can already implement something as described by (mirroring `createPresenter()`, don't make the Activity implement `MvpView` directly ) by using `ActivityMvpDelegate`. See [this](http://hannesdorfmann.com/mosby/mvp/) (scroll down until "Delegation headline". You can take a plain Activity and use the `ActivityMvpDelegate` provided by Mosby to implement an Activity that is just a lifecycle container component. 

Should we make this the default behaviour of Mosby? I'm not sure about it. On one hand, it sounds like a good and clean implementation detail to use the activity only as a lifecycle component. On the other hand it may requires writing more code and addition layers. Furthermore, your suggestion may or may require additional components for navigation (who starts intents, backstack management?, etc.). Also for non android experts it would be a little bit harder to use mosby.

As already said, in genreal I see the benefit of the architecture described by you. However I doubt that this is the use case of 90 % of the users of this library. Also I don't want to make Mosby that "complicated". I think the current way, just having a simple tiny, lightweight library is easy to maintain and allows others (like you) to build custom features on top of Mosby.

However, this doesn't mean that I'm saying **NO** to your suggestion. I want to involve other developers / community into this decision. I personally wouldn't need that extra abstraction/layer in my apps. However, if I am one developer of a bigger minority who don't need that extra abstraction, I think we should follow the majority and implement your suggestions. 

What do you think?

**Comment by joseprl89** [comment]
All very valid points.

I think you should close this issue mostly because of this part:

> Furthermore, your suggestion may or may require additional components for navigation (who starts intents, backstack management?, etc.) or forward / delegate lifecycle events to the real view (i.e. if view should stop a certain animation in onPause()). Also for non android experts it would be a little bit harder to get started with Mosby.

You are totally right there, we'd be introducing blurred lines into the library and making unclear where should a task be performed.

Probably this issue is too much of a "pedantic warning" :P

**Comment by sockeqwe** [comment]
I close it, but AS already said, I'm open to continue this discuss AS required by other developers

**Comment by lurbas** [comment]
I don't think additional component for navigation is a bad thing. I'm often introducing this kind of class. I like to have all logic connected with opening next screen, checking if I'm in one, or two-pane layout in separated place. Then my presenter doesn't care how the next screen looks like. it's just:
```
navigator.openScreen(DETAILS_SCREEN);
```
But I also don't think there should be any changes in mosby. It is a perfect base, and probably keeping it simple and well understood is the highest priority.
Every project is different and every project needs different approach. I think mosby should be the perfect starting point, not ultimate solution.

**Comment by sockeqwe** [comment]
I agree

**Comment by dimsuz** [comment]
Yes, please keep mosby a library which can serve as a simple and solid foundation for more complex solutions! :) I am finding that this is true right now, I hope this won't change.
