### ISSUE TITLE
MvpLceActivity can't see Dagger2 injections

### ISSUE THREAD

**Issue by jemshit** [sockeqwe/mosby#99]
I have `MyModule.java` which provides a Presenter for Activity:
```java
    @Provides
    public MyPresenter getMyPresenter(){
        return new MyPresenter();
    }
```
There is `MyComponent.java` which has:
```java
public interface MyComponent {
    void inject(MyActivity act);

    MyPresenter getMyPresenter();
}
``` 

Now i am trying to inject that Presenter in `MyActivity` and use it:
```java
public class MyActivity extends MvpLceActivity... {
@Inject MyPresenter myPresenter;
...
private void injectDependencies(){
    ....
}

 @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        injectDependencies();
        ....
}
@NonNull @Override
    public MyPresenter createPresenter() {
        return myPresenter;
}
...
}
```

It shows error:
```java
java.lang.NullPointerException: Presenter is null! Do you return null in createPresenter()?
```

**Comment by sockeqwe** [comment]
You have to call `injectDependencies()` before `super.onCreate()`  because the `super.onCreate()` will call `createPresenter()` internally.

Also, there is a variable `presenter` if you extend from a Mosby base class like `MvpLceActivity`. So in your `MyActivity` class you will have two variables pointing at the same presenter instance `myPresenter`  and ´presenter`. The later one comes as protected field from `MvpLceActivity`. 

I would recommend you to take a slightly different approach regarding dependency injection with dagger2. I would recommend to change your code to something like this:
```java
public class MyActivity extends MvpLceActivity... {
  private MyComponent component;
  ...
  
  private void injectDependencies(){
     myComponent = DaggerMyComponent.create();    
    ....
  }

 @Override
  public void onCreate(Bundle savedInstanceState) {
        injectDependencies();
        super.onCreate(savedInstanceState);
        ....
  }

  @NonNull @Override
  public MyPresenter createPresenter() {
        return component.getPresenter();
  }
  ...
}
```

**Comment by jemshit** [comment]
:+1:

**Comment by epetrenko** [comment]
@sockeqwe, @jemshit 

Let me share a solution, which I use for the case if [`dagger-android`](https://google.github.io/dagger/android) extension is used.

We can use `Provider<T>` injection. Code will look like the following:
```Java
public class MyActivity extends MvpLceActivity... {
  @Inject Provider<MyPresenter> myPresenterProvider;
  ...

 @Override
  public void onCreate(Bundle savedInstanceState) {
        AndroidInjection.inject(this);
        super.onCreate(savedInstanceState);
        ....
  }

  @NonNull @Override
  public MyPresenter createPresenter() {
        return myPresenterProvider.get();
  }
  ...
}
```
Here we do injection in Activity by calling just [`AndroidInjection.inject(this)`](https://github.com/google/dagger/blob/master/java/dagger/android/AndroidInjection.java) and don't need to have component instances.
